CREATE COLLATION IF NOT EXISTS public.nocase (provider = icu, deterministic = false, locale = 'und-u-ks-level2');

CREATE TABLE IF NOT EXISTS migration (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS year_status (name text PRIMARY KEY);
INSERT INTO year_status (name) VALUES ('open'), ('closed'), ('ongoing')
    ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS show_status (name text PRIMARY KEY);
INSERT INTO show_status (name) VALUES ('none'), ('draw'), ('partial'), ('full')
    ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS account_role (
    name text PRIMARY KEY,
    can_edit boolean NOT NULL DEFAULT false,
    can_view_restricted boolean NOT NULL DEFAULT false
);
INSERT INTO account_role (name, can_edit, can_view_restricted) VALUES
    ('user', false, false),
    ('editor', true, false),
    ('admin', true, true),
    ('owner', true, true)
    ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS account (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username text UNIQUE COLLATE public.nocase,
    email text,
    password bytea,
    salt bytea,
    approved boolean DEFAULT false,
    role text DEFAULT 'user' REFERENCES account_role (name) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS session (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL REFERENCES account (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    session_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS country (
    id text PRIMARY KEY COLLATE public.nocase,
    name text UNIQUE COLLATE public.nocase,
    is_participating boolean,
    pot smallint,
    available_from smallint DEFAULT 0,
    available_until smallint DEFAULT 9999,
    priority integer,
    cc3 text NOT NULL COLLATE public.nocase
);

CREATE TABLE IF NOT EXISTS year (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    status text REFERENCES year_status (name) ON UPDATE RESTRICT ON DELETE RESTRICT,
    host_id text COLLATE public.nocase REFERENCES country (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    special_name text,
    special_short_name text COLLATE public.nocase,
    CONSTRAINT year_special_name_check
    CHECK ((id >= 0 AND special_name IS NULL AND special_short_name IS NULL)
    OR (id < 0 AND special_name IS NOT NULL AND special_short_name IS NOT NULL)),
    CONSTRAINT year_special_short_name_key UNIQUE (special_short_name)
);

CREATE TABLE IF NOT EXISTS alternative_name (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    country_id text COLLATE public.nocase REFERENCES country (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    from_year_id bigint,
    to_year_id bigint,
    name text
);

CREATE TABLE IF NOT EXISTS language (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    tag text NOT NULL,
    extlang text,
    region text,
    subvariant text,
    suppress_script text,
    code3 text
);

CREATE TABLE IF NOT EXISTS song (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    submitter_id bigint REFERENCES account (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    country_id text COLLATE public.nocase REFERENCES country (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    year_id bigint REFERENCES year (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    title text,
    artist text,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    modified_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    native_title text,
    translated_lyrics text,
    romanized_lyrics text,
    native_lyrics text,
    video_link text,
    snippet_start integer,
    snippet_end integer,
    is_placeholder boolean,
    title_language_id bigint,
    native_language_id bigint,
    notes text,
    sources text,
    admin_approved boolean,
    poster_link text,
    entry_number integer NOT NULL DEFAULT 1,
    CONSTRAINT song_year_country_entry_key UNIQUE (year_id, country_id, entry_number)
);

CREATE TABLE IF NOT EXISTS song_language (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    song_id bigint REFERENCES song (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    language_id bigint REFERENCES language (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    priority smallint,
    UNIQUE(song_id, language_id),
    UNIQUE(song_id, priority)
);

CREATE TABLE IF NOT EXISTS point_system (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    number smallint
);

CREATE TABLE IF NOT EXISTS point (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    point_system_id bigint REFERENCES point_system (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    place smallint,
    score integer,
    UNIQUE(point_system_id, place)
);

CREATE TABLE IF NOT EXISTS show (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    year_id bigint REFERENCES year (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    point_system_id bigint REFERENCES point_system (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    show_name text COLLATE public.nocase,
    short_name text COLLATE public.nocase,
    voting_opens timestamptz,
    voting_closes timestamptz,
    date date,
    dtf smallint,
    sc smallint,
    special smallint,
    status text REFERENCES show_status (name) ON UPDATE RESTRICT ON DELETE RESTRICT,
    predictions_close timestamptz,
    UNIQUE(year_id, show_name)
);

CREATE TABLE IF NOT EXISTS song_show (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    song_id bigint REFERENCES song (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    show_id bigint REFERENCES show (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    running_order smallint,
    qualifier_order smallint,
    UNIQUE(song_id, show_id)
);

CREATE TABLE IF NOT EXISTS vote_set (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    voter_id bigint REFERENCES account (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    show_id bigint REFERENCES show (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    country_id text COLLATE public.nocase REFERENCES country (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    nickname text,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    ip_address inet,
    UNIQUE(voter_id, show_id)
);

CREATE TABLE IF NOT EXISTS vote (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    vote_set_id bigint REFERENCES vote_set (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    song_id bigint REFERENCES song (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    score integer,
    UNIQUE(vote_set_id, song_id)
);

CREATE TABLE IF NOT EXISTS api_token (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL REFERENCES account (id) ON DELETE CASCADE,
    token_hash bytea NOT NULL UNIQUE,
    label text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at timestamptz
);

CREATE TABLE IF NOT EXISTS prediction_set (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL REFERENCES account (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    show_id integer NOT NULL REFERENCES show (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, show_id)
);

CREATE TABLE IF NOT EXISTS prediction (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    set_id integer NOT NULL REFERENCES prediction_set (id) ON UPDATE RESTRICT ON DELETE CASCADE,
    song_id integer NOT NULL REFERENCES song (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    position integer NOT NULL,
    UNIQUE(set_id, song_id),
    UNIQUE(set_id, position)
);

CREATE TABLE IF NOT EXISTS country_show_results (
    country_id text NOT NULL REFERENCES country (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    country_name text NOT NULL,
    show_id integer NOT NULL REFERENCES show (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    show_name text,
    short_name text,
    year_id integer REFERENCES year (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    song_id bigint NOT NULL REFERENCES song (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    running_order integer,
    total_points integer NOT NULL,
    total_votes_received integer NOT NULL,
    point_distribution jsonb NOT NULL,
    place integer NOT NULL,
    total_countries integer NOT NULL,
    placement_percentage numeric(5,2) NOT NULL,
    max_possible_points integer NOT NULL,
    points_percentage numeric(5,2) NOT NULL,
    entry_status text,
    max_pts integer,
    total_voters integer,
    calculated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_country_show_results PRIMARY KEY (song_id, show_id)
);

CREATE TABLE IF NOT EXISTS country_year_results (
    country_id text NOT NULL REFERENCES country (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    country_name text NOT NULL,
    year_id integer REFERENCES year (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    song_id bigint NOT NULL REFERENCES song (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    place integer NOT NULL,
    total_countries integer NOT NULL,
    placement_percentage numeric(6, 3) NOT NULL
);

CREATE TABLE IF NOT EXISTS song_audit_log (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    song_id integer,
    event_type text NOT NULL,
    changed_by integer REFERENCES account(id) ON DELETE SET NULL,
    changed_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    song_title text,
    song_artist text,
    song_country_id text,
    song_year_id integer,
    changed_fields jsonb
);

CREATE INDEX IF NOT EXISTS idx_country_cc3 ON country (cc3);
CREATE INDEX IF NOT EXISTS idx_session_id ON session (session_id);
CREATE INDEX IF NOT EXISTS idx_song_submitter ON song (submitter_id);
CREATE INDEX IF NOT EXISTS idx_song_country ON song (country_id);
CREATE INDEX IF NOT EXISTS idx_song_year ON song (year_id);
CREATE INDEX IF NOT EXISTS idx_song_id_country_id ON song (id, country_id);
CREATE INDEX IF NOT EXISTS idx_vote_set_voter ON vote_set (voter_id);
CREATE INDEX IF NOT EXISTS idx_vote_set_show ON vote_set (show_id);
CREATE INDEX IF NOT EXISTS idx_song_show_song_show ON song_show (song_id, show_id);
CREATE INDEX IF NOT EXISTS idx_point_system_id_score ON point (point_system_id, score DESC);
CREATE INDEX IF NOT EXISTS idx_api_token_user_id ON api_token (user_id);
CREATE INDEX IF NOT EXISTS idx_api_token_hash ON api_token (token_hash);
CREATE INDEX IF NOT EXISTS idx_csr_show_id ON country_show_results (show_id);
CREATE INDEX IF NOT EXISTS idx_csr_year_id ON country_show_results (year_id);
CREATE INDEX IF NOT EXISTS idx_csr_show_place ON country_show_results (show_id, place);
CREATE INDEX IF NOT EXISTS idx_csr_point_distribution ON country_show_results USING gin (point_distribution);
CREATE INDEX IF NOT EXISTS song_audit_log_changed_at_idx ON song_audit_log (changed_at DESC);
CREATE INDEX IF NOT EXISTS song_audit_log_song_id_idx ON song_audit_log (song_id);
CREATE INDEX IF NOT EXISTS idx_song_language_language_id ON song_language (language_id);
CREATE INDEX IF NOT EXISTS idx_vote_song_id ON vote (song_id);

CREATE OR REPLACE FUNCTION redact_ip_address(p_show_id bigint)
RETURNS void AS $$
BEGIN
    UPDATE vote_set
    SET ip_address = NULL
    WHERE show_id = p_show_id;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION trigger_redact_ip_address()
RETURNS TRIGGER AS $$
BEGIN
    PERFORM redact_ip_address(NEW.id);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION refresh_show_results(p_show_id bigint)
RETURNS void AS $$
DECLARE
    v_max_point integer;
    v_inserted integer;
BEGIN
    SELECT MAX(p.score)
    INTO v_max_point
    FROM show sh
    JOIN point p ON p.point_system_id = sh.point_system_id
    WHERE sh.id = p_show_id;

    DELETE FROM country_show_results WHERE show_id = p_show_id;

    WITH si AS (
    SELECT sh.id, sh.year_id, sh.dtf, sh.sc, sh.special,
    sh.short_name, sh.show_name
    FROM show sh
    WHERE sh.id = p_show_id
    ),
    all_vote_sets AS (
    SELECT vs.*
    FROM vote_set vs
    WHERE vs.show_id = p_show_id
    ),
    voters_by_country AS (
    SELECT vs.country_id, COUNT(*) AS cnt
    FROM all_vote_sets vs
    WHERE vs.country_id IS NOT NULL
    GROUP BY vs.country_id
    ),
    totals AS (
    SELECT COUNT(*) AS total_valid FROM all_vote_sets
    ),
    point_counts AS (
    SELECT s.id AS song_id, s.country_id, v.score, COUNT(*) AS cnt
    FROM si
    JOIN song_show ss ON ss.show_id = si.id
    JOIN song s ON s.id = ss.song_id
    JOIN vote v ON v.song_id = s.id
    JOIN all_vote_sets vs ON vs.id = v.vote_set_id
    WHERE
    -- Modern rules (1979+) and specials (negative year_id): all votes count
    (si.year_id IS NULL OR si.year_id < 0 OR si.year_id >= 1979)
    -- 1965–1978: a country cannot vote for its own entry
    OR (si.year_id BETWEEN 1965 AND 1978
    AND vs.country_id IS DISTINCT FROM s.country_id)
    -- Pre-1965 (except 1960): also no self-votes
    OR (si.year_id >= 0 AND si.year_id < 1965 AND si.year_id <> 1960
    AND vs.country_id IS DISTINCT FROM s.country_id)
    -- 1960 special rule: self-vote allowed only if score = 1
    OR (si.year_id = 1960 AND (
    vs.country_id IS DISTINCT FROM s.country_id
    OR (vs.country_id = s.country_id AND v.score = 1)
    ))
    GROUP BY s.id, s.country_id, v.score
    ),
    aggregated AS (
    SELECT
    s.country_id,
    c.name AS country_name,
    si.id AS show_id,
    s.id AS song_id,
    ss.running_order,
    si.show_name,
    si.short_name,
    si.year_id,
    si.dtf, si.sc, si.special,
    COALESCE(SUM(pc.score * pc.cnt), 0) AS total_points,
    COALESCE(SUM(pc.cnt), 0) AS total_votes_received,
    COALESCE(
    JSONB_OBJECT_AGG(pc.score::text, pc.cnt ORDER BY pc.score DESC)
    FILTER (WHERE pc.score IS NOT NULL),
    '{}'::jsonb
    ) AS point_distribution,
    COALESCE(
    STRING_AGG(
    LPAD(pc.score::text, 3, '0') || ':' || LPAD(pc.cnt::text, 3, '0'),
    ',' ORDER BY pc.score DESC
    ) FILTER (WHERE pc.score IS NOT NULL),
    ''
    ) AS countback_string,
    (SELECT total_valid FROM totals) AS total_voters,
    CASE
    WHEN v_max_point IS NULL THEN 0
    WHEN si.year_id IS NULL OR si.year_id < 0 OR si.year_id >= 1979
    THEN v_max_point * (SELECT total_valid FROM totals)
    WHEN (si.year_id BETWEEN 1966 AND 1978)
    OR (si.year_id = 1965 AND si.short_name = 'f')
    THEN v_max_point * GREATEST(
    (SELECT total_valid FROM totals) - COALESCE(vbc.cnt, 0), 0)
    WHEN si.year_id = 1960
    THEN v_max_point * GREATEST(
    (SELECT total_valid FROM totals) - COALESCE(vbc.cnt, 0), 0)
    + COALESCE(vbc.cnt, 0)
    ELSE
    v_max_point * GREATEST(
    (SELECT total_valid FROM totals) - COALESCE(vbc.cnt, 0), 0)
    END AS max_possible_points_calc
    FROM si
    JOIN song_show ss ON ss.show_id = si.id
    JOIN song s ON s.id = ss.song_id
    JOIN country c ON c.id = s.country_id
    LEFT JOIN point_counts pc ON pc.song_id = s.id
    LEFT JOIN voters_by_country vbc ON vbc.country_id = s.country_id
    WHERE c.is_participating
    GROUP BY
    s.country_id, c.name, si.id, s.id, ss.running_order,
    si.show_name, si.short_name, si.year_id,
    si.dtf, si.sc, si.special, vbc.cnt
    ),
    ranked AS (
    SELECT
    a.*,
    DENSE_RANK() OVER (
    ORDER BY total_points DESC, total_votes_received DESC, countback_string DESC
    ) AS place,
    COUNT(*) OVER () AS total_countries
    FROM aggregated a
    )
    INSERT INTO country_show_results (
    country_id, country_name, show_id, show_name, short_name, year_id,
    song_id, running_order,
    total_points, total_votes_received, point_distribution,
    place, total_countries, placement_percentage,
    max_possible_points, points_percentage,
    entry_status, max_pts, total_voters
    )
    SELECT
    r.country_id,
    r.country_name,
    r.show_id,
    r.show_name,
    r.short_name,
    r.year_id,
    r.song_id,
    r.running_order,
    r.total_points,
    r.total_votes_received,
    r.point_distribution,
    r.place,
    r.total_countries,
    ROUND(
    CASE
    WHEN r.place = r.total_countries THEN 0
    WHEN r.total_countries > 1
    THEN ((r.total_countries - r.place)::numeric
    / (r.total_countries - 1)) * 100
    ELSE 100
    END, 2
    ) AS placement_percentage,
    COALESCE(r.max_possible_points_calc, 0) AS max_possible_points,
    ROUND(
    COALESCE(
    r.total_points::numeric / NULLIF(r.max_possible_points_calc::numeric, 0),
    0
    ) * 100, 2
    ) AS points_percentage,
    CASE
    WHEN r.short_name = 'f' THEN NULL
    WHEN r.place <= COALESCE(r.dtf, 0) THEN 'dtf'
    WHEN r.place <= COALESCE(r.dtf, 0) + COALESCE(r.special, 0) THEN 'special'
    WHEN r.place <= COALESCE(r.dtf, 0) + COALESCE(r.special, 0)
    + COALESCE(r.sc, 0) THEN 'sc'
    ELSE 'nq'
    END AS entry_status,
    v_max_point AS max_pts,
    r.total_voters
    FROM ranked r;

    GET DIAGNOSTICS v_inserted = ROW_COUNT;
    RAISE NOTICE 'Refreshed results for show %; rows=%', p_show_id, v_inserted;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION trigger_refresh_show_results_from_vote()
RETURNS TRIGGER AS $$
DECLARE
    v_show_id integer;
BEGIN
    SELECT show_id INTO v_show_id
    FROM vote_set
    WHERE id = COALESCE(NEW.vote_set_id, OLD.vote_set_id);

    IF v_show_id IS NOT NULL THEN
    PERFORM refresh_show_results(v_show_id);
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION trigger_refresh_show_results_from_vote_set()
RETURNS TRIGGER AS $$
DECLARE
    v_show_id integer;
BEGIN
    v_show_id := COALESCE(NEW.show_id, OLD.show_id);
    IF v_show_id IS NOT NULL THEN
    PERFORM refresh_show_results(v_show_id);
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

-- Recompute country_year_results for a year using a three-tier ranking.
CREATE OR REPLACE FUNCTION refresh_year_results(p_year_id bigint)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM country_year_results WHERE year_id = p_year_id;

    WITH finals AS (
    SELECT song_id, year_id, place AS f_place
    FROM country_show_results
    WHERE short_name = 'f' AND year_id = p_year_id
    ),
    sc_entries AS (
    SELECT song_id, year_id, place AS sc_place
    FROM country_show_results
    WHERE short_name = 'sc' AND year_id = p_year_id
    ),
    sf_entries AS (
    SELECT
    csr.song_id,
    csr.year_id,
    csr.points_percentage AS sf_pct,
    csr.total_voters AS sf_voters,
    csr.running_order AS sf_running_order,
    COALESCE(
    NULLIF(regexp_replace(csr.short_name, '\D', '', 'g'), '')::int,
    0
    ) AS sf_index,
    (
    SELECT STRING_AGG(
    LPAD(j.key, 3, '0') || ':' || LPAD(j.value, 3, '0'),
    ',' ORDER BY j.key::integer DESC
    )
    FROM jsonb_each_text(csr.point_distribution) AS j
    ) AS sf_countback
    FROM country_show_results csr
    WHERE (csr.short_name LIKE 'sf%' OR csr.short_name = 'sf')
    AND csr.year_id = p_year_id
    ),
    base AS (
    SELECT DISTINCT country_id, country_name, song_id, year_id
    FROM country_show_results
    WHERE year_id = p_year_id
    ),
    rank_space AS (
    SELECT
    b.country_id,
    b.country_name,
    b.year_id,
    b.song_id,
    CASE
    WHEN f.song_id IS NOT NULL THEN 1
    WHEN sc.song_id IS NOT NULL THEN 2
    WHEN sf.song_id IS NOT NULL THEN 3
    ELSE 4
    END AS tier,
    f.f_place,
    sc.sc_place,
    sf.sf_pct,
    sf.sf_voters,
    sf.sf_countback,
    sf.sf_running_order,
    sf.sf_index
    FROM base b
    LEFT JOIN finals f ON f.song_id = b.song_id AND f.year_id = b.year_id
    LEFT JOIN sc_entries sc ON sc.song_id = b.song_id AND sc.year_id = b.year_id
    LEFT JOIN sf_entries sf ON sf.song_id = b.song_id AND sf.year_id = b.year_id
    ),
    ranked_finals AS (
    SELECT *,
    ROW_NUMBER() OVER (ORDER BY f_place ASC) AS rank_in_tier
    FROM rank_space
    WHERE tier = 1
    ),
    ranked_sc AS (
    SELECT *,
    ROW_NUMBER() OVER (ORDER BY sc_place ASC) AS rank_in_tier
    FROM rank_space
    WHERE tier = 2
    ),
    ranked_sf AS (
    SELECT *,
    ROW_NUMBER() OVER (
    ORDER BY
    sf_pct DESC,
    sf_voters DESC,
    sf_countback DESC NULLS LAST,
    sf_running_order ASC NULLS LAST,
    sf_index ASC
    ) AS rank_in_tier
    FROM rank_space
    WHERE tier = 3
    ),
    ranked_other AS (
    SELECT *,
    ROW_NUMBER() OVER (ORDER BY song_id) AS rank_in_tier
    FROM rank_space
    WHERE tier = 4
    ),
    tier_sizes AS (
    SELECT
    (SELECT COUNT(*) FROM ranked_finals) AS n_f,
    (SELECT COUNT(*) FROM ranked_sc) AS n_sc,
    (SELECT COUNT(*) FROM ranked_sf) AS n_sf
    ),
    all_ranked AS (
    SELECT country_id, country_name, year_id, song_id,
    rank_in_tier::integer AS place
    FROM ranked_finals

    UNION ALL

    SELECT country_id, country_name, year_id, song_id,
    ((SELECT n_f FROM tier_sizes) + rank_in_tier)::integer
    FROM ranked_sc

    UNION ALL

    SELECT country_id, country_name, year_id, song_id,
    ((SELECT n_f + n_sc FROM tier_sizes) + rank_in_tier)::integer
    FROM ranked_sf

    UNION ALL

    SELECT country_id, country_name, year_id, song_id,
    ((SELECT n_f + n_sc + n_sf FROM tier_sizes) + rank_in_tier)::integer
    FROM ranked_other
    ),
    totals AS (
    SELECT COUNT(*) AS total_countries FROM all_ranked
    )
    INSERT INTO country_year_results
    (country_id, country_name, year_id, song_id,
    place, total_countries, placement_percentage)
    SELECT
    ar.country_id,
    ar.country_name,
    ar.year_id,
    ar.song_id,
    ar.place,
    t.total_countries,
    CASE
    WHEN t.total_countries = 1 THEN 100
    ELSE ROUND(
    ((t.total_countries - ar.place)::numeric
    / (t.total_countries - 1)::numeric) * 100,
    3)
    END AS placement_percentage
    FROM all_ranked ar
    CROSS JOIN totals t
    ORDER BY ar.place;
END;
$$;

CREATE OR REPLACE FUNCTION compute_country_year_results()
RETURNS trigger AS $func$
BEGIN
    IF NEW.status = 'closed' AND OLD.status IS DISTINCT FROM 'closed' THEN
    PERFORM refresh_year_results(NEW.id);
    END IF;
    RETURN NEW;
END;
$func$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION song_audit_trigger()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_user_id integer;
    v_changed jsonb := '{}';
    v_song_changed boolean := false;
    v_placeholder_changed boolean := false;
    v_ownership_changed boolean := false;
BEGIN
    v_user_id := NULLIF(current_setting('app.current_user_id', true), '')::integer;

    IF TG_OP = 'INSERT' THEN
    INSERT INTO song_audit_log
    (song_id, event_type, changed_by,
    song_title, song_artist, song_country_id, song_year_id)
    VALUES
    (NEW.id, 'create', v_user_id,
    NEW.title, NEW.artist, NEW.country_id, NEW.year_id);
    RETURN NEW;
    END IF;

    IF TG_OP = 'DELETE' THEN
    INSERT INTO song_audit_log
    (song_id, event_type, changed_by,
    song_title, song_artist, song_country_id, song_year_id)
    VALUES
    (OLD.id, 'delete', v_user_id,
    OLD.title, OLD.artist, OLD.country_id, OLD.year_id);
    RETURN OLD;
    END IF;

    IF TG_OP = 'UPDATE' THEN
    IF OLD.title IS DISTINCT FROM NEW.title THEN
    v_changed := v_changed || jsonb_build_object('title',
    jsonb_build_object('old', OLD.title, 'new', NEW.title));
    v_song_changed := true;
    END IF;

    IF OLD.artist IS DISTINCT FROM NEW.artist THEN
    v_changed := v_changed || jsonb_build_object('artist',
    jsonb_build_object('old', OLD.artist, 'new', NEW.artist));
    v_song_changed := true;
    END IF;

    IF OLD.native_title IS DISTINCT FROM NEW.native_title THEN
    v_changed := v_changed || jsonb_build_object('native_title',
    jsonb_build_object('old', OLD.native_title, 'new', NEW.native_title));
    END IF;

    IF OLD.video_link IS DISTINCT FROM NEW.video_link THEN
    v_changed := v_changed || jsonb_build_object('video_link',
    jsonb_build_object('old', OLD.video_link, 'new', NEW.video_link));
    END IF;

    IF OLD.poster_link IS DISTINCT FROM NEW.poster_link THEN
    v_changed := v_changed || jsonb_build_object('poster_link',
    jsonb_build_object('old', OLD.poster_link, 'new', NEW.poster_link));
    END IF;

    IF OLD.snippet_start IS DISTINCT FROM NEW.snippet_start THEN
    v_changed := v_changed || jsonb_build_object('snippet_start',
    jsonb_build_object('old', OLD.snippet_start::text, 'new', NEW.snippet_start::text));
    END IF;

    IF OLD.snippet_end IS DISTINCT FROM NEW.snippet_end THEN
    v_changed := v_changed || jsonb_build_object('snippet_end',
    jsonb_build_object('old', OLD.snippet_end::text, 'new', NEW.snippet_end::text));
    END IF;

    IF OLD.translated_lyrics IS DISTINCT FROM NEW.translated_lyrics THEN
    v_changed := v_changed || jsonb_build_object('translated_lyrics',
    jsonb_build_object('old', OLD.translated_lyrics, 'new', NEW.translated_lyrics));
    END IF;

    IF OLD.romanized_lyrics IS DISTINCT FROM NEW.romanized_lyrics THEN
    v_changed := v_changed || jsonb_build_object('romanized_lyrics',
    jsonb_build_object('old', OLD.romanized_lyrics, 'new', NEW.romanized_lyrics));
    END IF;

    IF OLD.native_lyrics IS DISTINCT FROM NEW.native_lyrics THEN
    v_changed := v_changed || jsonb_build_object('native_lyrics',
    jsonb_build_object('old', OLD.native_lyrics, 'new', NEW.native_lyrics));
    END IF;

    IF OLD.notes IS DISTINCT FROM NEW.notes THEN
    v_changed := v_changed || jsonb_build_object('notes',
    jsonb_build_object('old', OLD.notes, 'new', NEW.notes));
    END IF;

    IF OLD.sources IS DISTINCT FROM NEW.sources THEN
    v_changed := v_changed || jsonb_build_object('sources',
    jsonb_build_object('old', OLD.sources, 'new', NEW.sources));
    END IF;

    IF OLD.is_placeholder IS DISTINCT FROM NEW.is_placeholder THEN
    v_changed := v_changed || jsonb_build_object('is_placeholder',
    jsonb_build_object('old', OLD.is_placeholder::text, 'new', NEW.is_placeholder::text));
    v_placeholder_changed := true;
    END IF;

    IF OLD.admin_approved IS DISTINCT FROM NEW.admin_approved THEN
    v_changed := v_changed || jsonb_build_object('admin_approved',
    jsonb_build_object('old', OLD.admin_approved::text, 'new', NEW.admin_approved::text));
    END IF;

    IF OLD.submitter_id IS DISTINCT FROM NEW.submitter_id THEN
    v_changed := v_changed || jsonb_build_object('submitter_id',
    jsonb_build_object('old', OLD.submitter_id::text, 'new', NEW.submitter_id::text));
    v_ownership_changed := true;
    END IF;

    IF OLD.country_id IS DISTINCT FROM NEW.country_id THEN
    v_changed := v_changed || jsonb_build_object('country_id',
    jsonb_build_object('old', OLD.country_id, 'new', NEW.country_id));
    END IF;

    IF OLD.year_id IS DISTINCT FROM NEW.year_id THEN
    v_changed := v_changed || jsonb_build_object('year_id',
    jsonb_build_object('old', OLD.year_id::text, 'new', NEW.year_id::text));
    END IF;

    IF v_changed != '{}' THEN
    IF v_song_changed THEN
    INSERT INTO song_audit_log
    (song_id, event_type, changed_by,
    song_title, song_artist, song_country_id, song_year_id,
    changed_fields)
    VALUES
    (NEW.id, 'song_replacement', v_user_id,
    NEW.title, NEW.artist, NEW.country_id, NEW.year_id,
    jsonb_build_object('title',
    jsonb_build_object('old', OLD.title, 'new', NEW.title),
    'artist',
    jsonb_build_object('old', OLD.artist, 'new', NEW.artist)));
    END IF;

    IF v_placeholder_changed THEN
    INSERT INTO song_audit_log
    (song_id, event_type, changed_by,
    song_title, song_artist, song_country_id, song_year_id)
    VALUES
    (NEW.id,
    CASE WHEN NEW.is_placeholder THEN 'placeholder_on' ELSE 'placeholder_off' END,
    v_user_id,
    NEW.title, NEW.artist, NEW.country_id, NEW.year_id);
    END IF;

    IF v_ownership_changed THEN
    INSERT INTO song_audit_log
    (song_id, event_type, changed_by,
    song_title, song_artist, song_country_id, song_year_id,
    changed_fields)
    VALUES
    (NEW.id, 'ownership_change', v_user_id,
    NEW.title, NEW.artist, NEW.country_id, NEW.year_id,
    jsonb_build_object('submitter_id',
    jsonb_build_object('old', OLD.submitter_id::text, 'new', NEW.submitter_id::text)));
    END IF;

    IF (v_changed - CASE WHEN v_song_changed THEN 'title' ELSE '' END
    - CASE WHEN v_song_changed THEN 'artist' ELSE '' END
    - CASE WHEN v_placeholder_changed THEN 'is_placeholder' ELSE '' END
    - CASE WHEN v_ownership_changed THEN 'submitter_id' ELSE '' END) != '{}' THEN
    INSERT INTO song_audit_log
    (song_id, event_type, changed_by,
    song_title, song_artist, song_country_id, song_year_id,
    changed_fields)
    VALUES
    (NEW.id, 'song_modification', v_user_id,
    NEW.title, NEW.artist, NEW.country_id, NEW.year_id,
    v_changed - CASE WHEN v_song_changed THEN 'title' ELSE '' END
    - CASE WHEN v_song_changed THEN 'artist' ELSE '' END
    - CASE WHEN v_placeholder_changed THEN 'is_placeholder' ELSE '' END
    - CASE WHEN v_ownership_changed THEN 'submitter_id' ELSE '' END);
    END IF;
    END IF;

    RETURN NEW;
    END IF;

    RETURN NULL;
END;
$$;

-- Move the bias-page queries out of Python. They're parameterized by user_id
-- so a plain view doesn't fit; set-returning SQL functions give us the same
-- call shape (SELECT * FROM fn(%s)) while keeping the query logic in the DB.
--
-- Optimized vs. the original Python inline versions:
--   * all_votes + user_votes merged via FILTER (one scan instead of two).
--   * all_totals + user_total merged (one scan instead of two).
--   * Redundant re-joins/re-filters of `show` dropped — user_shows already
--     restricts to status='full' (and year_id > 0 for the country variant,
--     which excludes specials), so re-filtering downstream was pointless
--     work.
--   * combined is a 3-way FULL OUTER JOIN instead of 4-way.

CREATE OR REPLACE FUNCTION user_country_bias(p_user_id bigint)
RETURNS TABLE (
    country_id text,
    country_name text,
    parts bigint,
    user_given bigint,
    user_max numeric,
    user_ratio numeric,
    total_given bigint,
    total_max numeric,
    total_ratio numeric,
    bias numeric,
    bias_class text
)
LANGUAGE sql STABLE AS $$
WITH user_shows AS (
    SELECT s.id AS show_id
    FROM vote_set vs
    JOIN show s ON s.id = vs.show_id
    WHERE vs.voter_id = p_user_id
      AND s.status = 'full'
      AND s.year_id > 0
    GROUP BY s.id
),
songs_available AS (
    SELECT s.country_id, COUNT(*) AS songs_available
    FROM user_shows us
    JOIN song_show ss ON ss.show_id = us.show_id
    JOIN song s ON s.id = ss.song_id
    WHERE s.submitter_id <> p_user_id
    GROUP BY s.country_id
),
key_votes AS (
    SELECT s.country_id,
        SUM(v.score) AS total_given,
        COALESCE(SUM(v.score) FILTER (WHERE vs.voter_id = p_user_id), 0) AS user_given,
        COUNT(*) FILTER (WHERE vs.voter_id = p_user_id) AS user_votes
    FROM user_shows us
    JOIN vote_set vs ON vs.show_id = us.show_id
    JOIN vote v ON v.vote_set_id = vs.id
    JOIN song s ON s.id = v.song_id
    WHERE s.submitter_id <> p_user_id
    GROUP BY s.country_id
),
totals AS (
    SELECT COALESCE(SUM(total_given), 0) AS total_given_all,
        COALESCE(SUM(user_given), 0) AS user_total_given
    FROM key_votes
),
show_user_points AS (
    SELECT us.show_id, SUM(v.score) AS user_points_in_show
    FROM user_shows us
    JOIN vote_set vs ON vs.show_id = us.show_id AND vs.voter_id = p_user_id
    JOIN vote v ON v.vote_set_id = vs.id
    GROUP BY us.show_id
),
user_exposure AS (
    SELECT cs.country_id,
        COALESCE(SUM(sup.user_points_in_show), 0) AS exposure_points
    FROM (
        SELECT DISTINCT us.show_id, s.country_id
        FROM user_shows us
        JOIN song_show ss ON ss.show_id = us.show_id
        JOIN song s ON s.id = ss.song_id
        WHERE s.submitter_id <> p_user_id
    ) cs
    LEFT JOIN show_user_points sup ON sup.show_id = cs.show_id
    GROUP BY cs.country_id
),
combined AS (
    SELECT COALESCE(sa.country_id, kv.country_id, ue.country_id) AS country_id,
        COALESCE(sa.songs_available, 0) AS songs_available,
        COALESCE(kv.user_given, 0) AS user_given,
        COALESCE(kv.user_votes, 0) AS user_votes,
        COALESCE(kv.total_given, 0) AS total_given,
        COALESCE(ue.exposure_points, 0) AS exposure_points
    FROM songs_available sa
    FULL OUTER JOIN key_votes kv ON kv.country_id = sa.country_id
    FULL OUTER JOIN user_exposure ue ON ue.country_id = COALESCE(sa.country_id, kv.country_id)
),
bias_values AS (
    SELECT c.*,
        t.user_total_given::numeric AS user_total_given,
        t.total_given_all::numeric AS total_given_all,
        CASE WHEN t.user_total_given > 0
            THEN c.user_given::numeric / t.user_total_given
            ELSE 0 END AS q_c,
        CASE WHEN t.total_given_all > 0
            THEN c.total_given::numeric / t.total_given_all
            ELSE 0 END AS p_c
    FROM combined c
    CROSS JOIN totals t
),
scored AS (
    SELECT bv.*,
        bv.exposure_points::numeric AS n_c,
        CASE WHEN bv.p_c > 0 AND bv.exposure_points > 0
            THEN (bv.exposure_points / (bv.exposure_points + 100.0)) * bv.q_c
               + (100.0 / (bv.exposure_points + 100.0)) * bv.p_c
            WHEN bv.p_c > 0 THEN bv.p_c
            ELSE 0 END AS q_hat
    FROM bias_values bv
),
final_bias AS (
    SELECT s.*,
        CASE WHEN s.p_c > 0
            THEN (s.q_hat - s.p_c) / (s.p_c + 0.0005)
            ELSE 0 END AS bias
    FROM scored s
)
SELECT fb.country_id,
    c.name AS country_name,
    fb.songs_available AS parts,
    fb.user_given,
    fb.user_total_given AS user_max,
    fb.q_c AS user_ratio,
    fb.total_given,
    fb.total_given_all AS total_max,
    fb.p_c AS total_ratio,
    fb.bias,
    CASE
        WHEN fb.songs_available < 5 OR fb.n_c < 50 THEN 'inconclusive'
        WHEN fb.bias < -0.5 THEN 'very-negative'
        WHEN fb.bias < -0.1 THEN 'negative'
        WHEN fb.bias < 0.1 THEN 'neutral'
        WHEN fb.bias < 0.5 THEN 'positive'
        ELSE 'very-positive'
    END AS bias_class
FROM final_bias fb
LEFT JOIN country c ON c.id = fb.country_id
WHERE fb.songs_available > 0
ORDER BY fb.bias DESC, fb.songs_available, fb.p_c
$$;


CREATE OR REPLACE FUNCTION user_submitter_bias(p_user_id bigint)
RETURNS TABLE (
    submitter_id bigint,
    submitter_name text,
    parts bigint,
    user_given bigint,
    submitter_given bigint,
    total_given bigint,
    points_deficit bigint,
    user_max numeric,
    all_max numeric,
    user_ratio numeric,
    total_ratio numeric,
    reciprocal_bias numeric,
    bias numeric,
    bias_class text,
    reciprocal_bias_class text
)
LANGUAGE sql STABLE AS $$
WITH user_shows AS (
    SELECT s.id AS show_id
    FROM vote_set vs
    JOIN show s ON s.id = vs.show_id
    WHERE vs.voter_id = p_user_id
      AND s.status = 'full'
    GROUP BY s.id
),
songs_available AS (
    SELECT s.submitter_id, COUNT(DISTINCT s.id) AS songs_available
    FROM user_shows us
    JOIN song_show ss ON ss.show_id = us.show_id
    JOIN song s ON s.id = ss.song_id
    WHERE s.submitter_id <> p_user_id
    GROUP BY s.submitter_id
),
key_votes AS (
    SELECT s.submitter_id,
        SUM(v.score) AS total_given,
        COALESCE(SUM(v.score) FILTER (WHERE vs.voter_id = p_user_id), 0) AS user_given,
        COUNT(*) FILTER (WHERE vs.voter_id = p_user_id) AS user_votes
    FROM user_shows us
    JOIN vote_set vs ON vs.show_id = us.show_id
    JOIN vote v ON v.vote_set_id = vs.id
    JOIN song s ON s.id = v.song_id
    WHERE s.submitter_id <> p_user_id
    GROUP BY s.submitter_id
),
totals AS (
    SELECT COALESCE(SUM(total_given), 0) AS total_given_all,
        COALESCE(SUM(user_given), 0) AS user_total_given
    FROM key_votes
),
show_user_points AS (
    SELECT us.show_id, SUM(v.score) AS user_points_in_show
    FROM user_shows us
    JOIN vote_set vs ON vs.show_id = us.show_id AND vs.voter_id = p_user_id
    JOIN vote v ON v.vote_set_id = vs.id
    GROUP BY us.show_id
),
user_exposure AS (
    SELECT ss.submitter_id,
        COALESCE(SUM(sup.user_points_in_show), 0) AS exposure_points
    FROM (
        SELECT DISTINCT us.show_id, s.submitter_id
        FROM user_shows us
        JOIN song_show ss ON ss.show_id = us.show_id
        JOIN song s ON s.id = ss.song_id
        WHERE s.submitter_id <> p_user_id
    ) ss
    LEFT JOIN show_user_points sup ON sup.show_id = ss.show_id
    GROUP BY ss.submitter_id
),
reciprocal_points AS (
    SELECT vs.voter_id AS submitter_id,
        SUM(v.score) AS pts_target_to_user
    FROM vote_set vs
    JOIN vote v ON v.vote_set_id = vs.id
    JOIN song s ON s.id = v.song_id
    JOIN show sh ON sh.id = vs.show_id
    WHERE s.submitter_id = p_user_id
      AND vs.voter_id <> p_user_id
      AND sh.status = 'full'
    GROUP BY vs.voter_id
),
combined AS (
    SELECT COALESCE(sa.submitter_id, kv.submitter_id, ue.submitter_id) AS submitter_id,
        COALESCE(sa.songs_available, 0) AS songs_available,
        COALESCE(kv.user_given, 0) AS user_given,
        COALESCE(kv.user_votes, 0) AS user_votes,
        COALESCE(kv.total_given, 0) AS total_given,
        COALESCE(ue.exposure_points, 0) AS exposure_points
    FROM songs_available sa
    FULL OUTER JOIN key_votes kv ON kv.submitter_id = sa.submitter_id
    FULL OUTER JOIN user_exposure ue ON ue.submitter_id = COALESCE(sa.submitter_id, kv.submitter_id)
),
bias_values AS (
    SELECT c.*,
        t.user_total_given::numeric AS user_total_given,
        t.total_given_all::numeric AS total_given_all,
        CASE WHEN t.user_total_given > 0
            THEN c.user_given::numeric / t.user_total_given
            ELSE 0 END AS q_s,
        CASE WHEN t.total_given_all > 0
            THEN c.total_given::numeric / t.total_given_all
            ELSE 0 END AS p_s
    FROM combined c
    CROSS JOIN totals t
),
scored AS (
    SELECT bv.*,
        bv.exposure_points::numeric AS n_s,
        CASE WHEN bv.p_s > 0 AND bv.exposure_points > 0
            THEN (bv.exposure_points / (bv.exposure_points + 100.0)) * bv.q_s
               + (100.0 / (bv.exposure_points + 100.0)) * bv.p_s
            WHEN bv.p_s > 0 THEN bv.p_s
            ELSE 0 END AS q_hat
    FROM bias_values bv
),
final_bias AS (
    SELECT s.*,
        rp.pts_target_to_user,
        CASE WHEN s.p_s > 0
            THEN (s.q_hat - s.p_s) / (s.p_s + 0.0005)
            ELSE 0 END AS bias
    FROM scored s
    LEFT JOIN reciprocal_points rp ON rp.submitter_id = s.submitter_id
)
SELECT fb.submitter_id,
    a.username AS submitter_name,
    fb.songs_available AS parts,
    fb.user_given,
    COALESCE(fb.pts_target_to_user, 0) AS submitter_given,
    fb.total_given,
    (fb.user_given - COALESCE(fb.pts_target_to_user, 0)) AS points_deficit,
    fb.user_total_given AS user_max,
    fb.total_given_all AS all_max,
    fb.q_s AS user_ratio,
    fb.p_s AS total_ratio,
    CASE WHEN fb.pts_target_to_user > 0
        THEN (fb.user_given::numeric / fb.pts_target_to_user) - 1
        ELSE 0 END AS reciprocal_bias,
    fb.bias,
    CASE
        WHEN fb.songs_available < 5 OR fb.n_s < 50 THEN 'inconclusive'
        WHEN fb.bias < -0.5 THEN 'very-negative'
        WHEN fb.bias < -0.1 THEN 'negative'
        WHEN fb.bias < 0.1 THEN 'neutral'
        WHEN fb.bias < 0.5 THEN 'positive'
        ELSE 'very-positive'
    END AS bias_class,
    CASE
        WHEN fb.songs_available < 5
          OR fb.pts_target_to_user IS NULL
          OR fb.pts_target_to_user = 0 THEN 'inconclusive'
        WHEN (fb.user_given::numeric / fb.pts_target_to_user) - 1 < -0.5 THEN 'very-negative'
        WHEN (fb.user_given::numeric / fb.pts_target_to_user) - 1 < -0.1 THEN 'negative'
        WHEN (fb.user_given::numeric / fb.pts_target_to_user) - 1 < 0.1 THEN 'neutral'
        WHEN (fb.user_given::numeric / fb.pts_target_to_user) - 1 < 0.5 THEN 'positive'
        ELSE 'very-positive'
    END AS reciprocal_bias_class
FROM final_bias fb
LEFT JOIN account a ON a.id = fb.submitter_id
WHERE fb.songs_available > 0
ORDER BY fb.bias DESC, fb.songs_available, fb.p_s
$$;

-- Inverse bias functions: the forward ones (user_country_bias,
-- user_submitter_bias) answer "for voter X, which targets are they biased
-- for/against?". These answer "for target X, which voters are biased
-- for/against them?".
--
-- Same formula, same CTE skeleton — just with the iteration key flipped.
-- For each voter v, we aggregate over v's qualifying shows and compute
-- p_c (population's allocation to the target in v's shows) and q_c
-- (v's allocation to the target), then the smoothed bias.

CREATE OR REPLACE FUNCTION country_voter_bias(p_country_id text)
RETURNS TABLE (
    voter_id bigint,
    voter_name text,
    parts bigint,
    user_given bigint,
    user_max numeric,
    user_ratio numeric,
    total_given bigint,
    total_max numeric,
    total_ratio numeric,
    bias numeric,
    bias_class text
)
LANGUAGE sql STABLE AS $$
WITH voter_shows AS (
    SELECT vs.voter_id, vs.show_id
    FROM vote_set vs
    JOIN show sh ON sh.id = vs.show_id
    WHERE sh.status = 'full'
      AND sh.year_id > 0
),
songs_available AS (
    SELECT vss.voter_id, COUNT(*) AS songs_available
    FROM voter_shows vss
    JOIN song_show ss ON ss.show_id = vss.show_id
    JOIN song s ON s.id = ss.song_id
    WHERE s.country_id = p_country_id
      AND s.submitter_id <> vss.voter_id
    GROUP BY vss.voter_id
),
key_votes AS (
    SELECT vss.voter_id,
        COALESCE(SUM(v.score) FILTER (WHERE s.country_id = p_country_id), 0) AS total_given,
        SUM(v.score) AS total_given_all,
        COALESCE(SUM(v.score) FILTER (WHERE s.country_id = p_country_id
                                        AND inner_vs.voter_id = vss.voter_id), 0) AS user_given,
        COALESCE(SUM(v.score) FILTER (WHERE inner_vs.voter_id = vss.voter_id), 0) AS user_total_given
    FROM voter_shows vss
    JOIN vote_set inner_vs ON inner_vs.show_id = vss.show_id
    JOIN vote v ON v.vote_set_id = inner_vs.id
    JOIN song s ON s.id = v.song_id
    WHERE s.submitter_id <> vss.voter_id
    GROUP BY vss.voter_id
),
show_user_points AS (
    SELECT vss.voter_id, vss.show_id, SUM(v.score) AS points_in_show
    FROM voter_shows vss
    JOIN vote_set vs ON vs.show_id = vss.show_id AND vs.voter_id = vss.voter_id
    JOIN vote v ON v.vote_set_id = vs.id
    JOIN song s ON s.id = v.song_id
    WHERE s.submitter_id <> vss.voter_id
    GROUP BY vss.voter_id, vss.show_id
),
user_exposure AS (
    SELECT es.voter_id,
        COALESCE(SUM(sup.points_in_show), 0) AS exposure_points
    FROM (
        SELECT DISTINCT vss.voter_id, vss.show_id
        FROM voter_shows vss
        JOIN song_show ss ON ss.show_id = vss.show_id
        JOIN song s ON s.id = ss.song_id
        WHERE s.country_id = p_country_id
          AND s.submitter_id <> vss.voter_id
    ) es
    LEFT JOIN show_user_points sup
        ON sup.voter_id = es.voter_id AND sup.show_id = es.show_id
    GROUP BY es.voter_id
),
combined AS (
    SELECT COALESCE(sa.voter_id, kv.voter_id, ue.voter_id) AS voter_id,
        COALESCE(sa.songs_available, 0) AS songs_available,
        COALESCE(kv.user_given, 0) AS user_given,
        COALESCE(kv.total_given, 0) AS total_given,
        COALESCE(kv.total_given_all, 0) AS total_given_all,
        COALESCE(kv.user_total_given, 0) AS user_total_given,
        COALESCE(ue.exposure_points, 0) AS exposure_points
    FROM songs_available sa
    FULL OUTER JOIN key_votes kv ON kv.voter_id = sa.voter_id
    FULL OUTER JOIN user_exposure ue ON ue.voter_id = COALESCE(sa.voter_id, kv.voter_id)
),
bias_values AS (
    SELECT c.*,
        CASE WHEN c.user_total_given > 0
            THEN c.user_given::numeric / c.user_total_given
            ELSE 0 END AS q_c,
        CASE WHEN c.total_given_all > 0
            THEN c.total_given::numeric / c.total_given_all
            ELSE 0 END AS p_c
    FROM combined c
),
scored AS (
    SELECT bv.*,
        bv.exposure_points::numeric AS n_c,
        CASE WHEN bv.p_c > 0 AND bv.exposure_points > 0
            THEN (bv.exposure_points / (bv.exposure_points + 100.0)) * bv.q_c
               + (100.0 / (bv.exposure_points + 100.0)) * bv.p_c
            WHEN bv.p_c > 0 THEN bv.p_c
            ELSE 0 END AS q_hat
    FROM bias_values bv
),
final_bias AS (
    SELECT s.*,
        CASE WHEN s.p_c > 0
            THEN (s.q_hat - s.p_c) / (s.p_c + 0.0005)
            ELSE 0 END AS bias
    FROM scored s
)
SELECT fb.voter_id,
    a.username AS voter_name,
    fb.songs_available AS parts,
    fb.user_given,
    fb.user_total_given AS user_max,
    fb.q_c AS user_ratio,
    fb.total_given,
    fb.total_given_all AS total_max,
    fb.p_c AS total_ratio,
    fb.bias,
    CASE
        WHEN fb.songs_available < 5 OR fb.n_c < 50 THEN 'inconclusive'
        WHEN fb.bias < -0.5 THEN 'very-negative'
        WHEN fb.bias < -0.1 THEN 'negative'
        WHEN fb.bias < 0.1 THEN 'neutral'
        WHEN fb.bias < 0.5 THEN 'positive'
        ELSE 'very-positive'
    END AS bias_class
FROM final_bias fb
LEFT JOIN account a ON a.id = fb.voter_id
WHERE fb.songs_available > 0
ORDER BY fb.bias DESC, fb.songs_available, fb.p_c
$$;


CREATE OR REPLACE FUNCTION submitter_voter_bias(p_submitter_id bigint)
RETURNS TABLE (
    voter_id bigint,
    voter_name text,
    parts bigint,
    user_given bigint,
    submitter_given bigint,
    total_given bigint,
    points_deficit bigint,
    user_max numeric,
    all_max numeric,
    user_ratio numeric,
    total_ratio numeric,
    reciprocal_bias numeric,
    bias numeric,
    bias_class text,
    reciprocal_bias_class text
)
LANGUAGE sql STABLE AS $$
WITH voter_shows AS (
    SELECT vs.voter_id, vs.show_id
    FROM vote_set vs
    JOIN show sh ON sh.id = vs.show_id
    WHERE sh.status = 'full'
),
songs_available AS (
    SELECT vss.voter_id, COUNT(DISTINCT s.id) AS songs_available
    FROM voter_shows vss
    JOIN song_show ss ON ss.show_id = vss.show_id
    JOIN song s ON s.id = ss.song_id
    WHERE s.submitter_id = p_submitter_id
      AND s.submitter_id <> vss.voter_id
    GROUP BY vss.voter_id
),
key_votes AS (
    SELECT vss.voter_id,
        COALESCE(SUM(v.score) FILTER (WHERE s.submitter_id = p_submitter_id), 0) AS total_given,
        SUM(v.score) AS total_given_all,
        COALESCE(SUM(v.score) FILTER (WHERE s.submitter_id = p_submitter_id
                                        AND inner_vs.voter_id = vss.voter_id), 0) AS user_given,
        COALESCE(SUM(v.score) FILTER (WHERE inner_vs.voter_id = vss.voter_id), 0) AS user_total_given
    FROM voter_shows vss
    JOIN vote_set inner_vs ON inner_vs.show_id = vss.show_id
    JOIN vote v ON v.vote_set_id = inner_vs.id
    JOIN song s ON s.id = v.song_id
    WHERE s.submitter_id <> vss.voter_id
    GROUP BY vss.voter_id
),
show_user_points AS (
    SELECT vss.voter_id, vss.show_id, SUM(v.score) AS points_in_show
    FROM voter_shows vss
    JOIN vote_set vs ON vs.show_id = vss.show_id AND vs.voter_id = vss.voter_id
    JOIN vote v ON v.vote_set_id = vs.id
    JOIN song s ON s.id = v.song_id
    WHERE s.submitter_id <> vss.voter_id
    GROUP BY vss.voter_id, vss.show_id
),
user_exposure AS (
    SELECT es.voter_id,
        COALESCE(SUM(sup.points_in_show), 0) AS exposure_points
    FROM (
        SELECT DISTINCT vss.voter_id, vss.show_id
        FROM voter_shows vss
        JOIN song_show ss ON ss.show_id = vss.show_id
        JOIN song s ON s.id = ss.song_id
        WHERE s.submitter_id = p_submitter_id
          AND s.submitter_id <> vss.voter_id
    ) es
    LEFT JOIN show_user_points sup
        ON sup.voter_id = es.voter_id AND sup.show_id = es.show_id
    GROUP BY es.voter_id
),
-- Reciprocal: for each voter v, how many points did the target submitter
-- give to v's songs? Group target's votes by the submitter of the target's
-- chosen songs.
reciprocal_from_target AS (
    SELECT s.submitter_id AS voter_id,
        SUM(v.score) AS pts_target_to_voter
    FROM vote_set vs
    JOIN vote v ON v.vote_set_id = vs.id
    JOIN song s ON s.id = v.song_id
    JOIN show sh ON sh.id = vs.show_id
    WHERE vs.voter_id = p_submitter_id
      AND s.submitter_id <> p_submitter_id
      AND sh.status = 'full'
    GROUP BY s.submitter_id
),
combined AS (
    SELECT COALESCE(sa.voter_id, kv.voter_id, ue.voter_id) AS voter_id,
        COALESCE(sa.songs_available, 0) AS songs_available,
        COALESCE(kv.user_given, 0) AS user_given,
        COALESCE(kv.total_given, 0) AS total_given,
        COALESCE(kv.total_given_all, 0) AS total_given_all,
        COALESCE(kv.user_total_given, 0) AS user_total_given,
        COALESCE(ue.exposure_points, 0) AS exposure_points
    FROM songs_available sa
    FULL OUTER JOIN key_votes kv ON kv.voter_id = sa.voter_id
    FULL OUTER JOIN user_exposure ue ON ue.voter_id = COALESCE(sa.voter_id, kv.voter_id)
),
bias_values AS (
    SELECT c.*,
        CASE WHEN c.user_total_given > 0
            THEN c.user_given::numeric / c.user_total_given
            ELSE 0 END AS q_s,
        CASE WHEN c.total_given_all > 0
            THEN c.total_given::numeric / c.total_given_all
            ELSE 0 END AS p_s
    FROM combined c
),
scored AS (
    SELECT bv.*,
        bv.exposure_points::numeric AS n_s,
        CASE WHEN bv.p_s > 0 AND bv.exposure_points > 0
            THEN (bv.exposure_points / (bv.exposure_points + 100.0)) * bv.q_s
               + (100.0 / (bv.exposure_points + 100.0)) * bv.p_s
            WHEN bv.p_s > 0 THEN bv.p_s
            ELSE 0 END AS q_hat
    FROM bias_values bv
),
final_bias AS (
    SELECT s.*,
        rft.pts_target_to_voter,
        CASE WHEN s.p_s > 0
            THEN (s.q_hat - s.p_s) / (s.p_s + 0.0005)
            ELSE 0 END AS bias
    FROM scored s
    LEFT JOIN reciprocal_from_target rft ON rft.voter_id = s.voter_id
)
SELECT fb.voter_id,
    a.username AS voter_name,
    fb.songs_available AS parts,
    fb.user_given,
    COALESCE(fb.pts_target_to_voter, 0) AS submitter_given,
    fb.total_given,
    (fb.user_given - COALESCE(fb.pts_target_to_voter, 0)) AS points_deficit,
    fb.user_total_given AS user_max,
    fb.total_given_all AS all_max,
    fb.q_s AS user_ratio,
    fb.p_s AS total_ratio,
    CASE WHEN fb.pts_target_to_voter > 0
        THEN (fb.user_given::numeric / fb.pts_target_to_voter) - 1
        ELSE 0 END AS reciprocal_bias,
    fb.bias,
    CASE
        WHEN fb.songs_available < 5 OR fb.n_s < 50 THEN 'inconclusive'
        WHEN fb.bias < -0.5 THEN 'very-negative'
        WHEN fb.bias < -0.1 THEN 'negative'
        WHEN fb.bias < 0.1 THEN 'neutral'
        WHEN fb.bias < 0.5 THEN 'positive'
        ELSE 'very-positive'
    END AS bias_class,
    CASE
        WHEN fb.songs_available < 5
          OR fb.pts_target_to_voter IS NULL
          OR fb.pts_target_to_voter = 0 THEN 'inconclusive'
        WHEN (fb.user_given::numeric / fb.pts_target_to_voter) - 1 < -0.5 THEN 'very-negative'
        WHEN (fb.user_given::numeric / fb.pts_target_to_voter) - 1 < -0.1 THEN 'negative'
        WHEN (fb.user_given::numeric / fb.pts_target_to_voter) - 1 < 0.1 THEN 'neutral'
        WHEN (fb.user_given::numeric / fb.pts_target_to_voter) - 1 < 0.5 THEN 'positive'
        ELSE 'very-positive'
    END AS reciprocal_bias_class
FROM final_bias fb
LEFT JOIN account a ON a.id = fb.voter_id
WHERE fb.songs_available > 0
ORDER BY fb.bias DESC, fb.songs_available, fb.p_s
$$;

DROP TRIGGER IF EXISTS redact_points_on_voting_close ON show;
CREATE TRIGGER redact_points_on_voting_close
    AFTER UPDATE OF status ON show
    FOR EACH ROW
    WHEN (NEW.status = 'full' AND OLD.status IS DISTINCT FROM 'full')
    EXECUTE FUNCTION trigger_redact_ip_address();

DROP TRIGGER IF EXISTS trg_refresh_show_results_on_vote ON vote;
CREATE TRIGGER trg_refresh_show_results_on_vote
    AFTER INSERT OR UPDATE OR DELETE ON vote
    FOR EACH ROW
    EXECUTE FUNCTION trigger_refresh_show_results_from_vote();

DROP TRIGGER IF EXISTS trg_refresh_show_results_on_vote_set ON vote_set;
CREATE TRIGGER trg_refresh_show_results_on_vote_set
    AFTER INSERT OR UPDATE OR DELETE ON vote_set
    FOR EACH ROW
    EXECUTE FUNCTION trigger_refresh_show_results_from_vote_set();

DROP TRIGGER IF EXISTS trg_compute_country_year_results ON year;
CREATE TRIGGER trg_compute_country_year_results
    AFTER UPDATE OF status ON year
    FOR EACH ROW
    WHEN (NEW.status = 'closed' AND OLD.status IS DISTINCT FROM 'closed')
    EXECUTE FUNCTION compute_country_year_results();

DROP TRIGGER IF EXISTS song_audit ON song;
CREATE TRIGGER song_audit
    AFTER INSERT OR UPDATE OR DELETE ON song
    FOR EACH ROW
    EXECUTE FUNCTION song_audit_trigger();