CREATE COLLATION IF NOT EXISTS public.nocase (provider = icu, deterministic = false, locale = 'und-u-ks-level2');

CREATE TABLE IF NOT EXISTS migration (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS account (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username text UNIQUE COLLATE nocase,
    email text,
    password bytea,
    salt bytea,
    approved bigint DEFAULT 0,
    role text DEFAULT 'user'
);

CREATE TABLE IF NOT EXISTS session (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL REFERENCES account (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    session_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS country (
    id text PRIMARY KEY COLLATE public.nocase,
    name text UNIQUE COLLATE public.nocase,
    is_participating boolean,
    pot bigint,
    available_from bigint DEFAULT 0,
    available_until bigint DEFAULT 9999,
    priority integer,
    cc3 text NOT NULL COLLATE public.nocase
);

CREATE TABLE IF NOT EXISTS alternative_name (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    country_id text COLLATE public.nocase REFERENCES country (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    from_year_id bigint,
    to_year_id bigint,
    name text
);

CREATE TABLE IF NOT EXISTS year (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    closed bigint,
    host_id text COLLATE public.nocase REFERENCES country (id) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS language (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    tag text NOT NULL,
    extlang text,
    region text,
    subvariant text,
    suppress_script text,
    code3 text
);

CREATE TABLE IF NOT EXISTS song (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    submitter_id bigint REFERENCES account (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    country_id text COLLATE public.nocase REFERENCES country (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    year_id bigint REFERENCES year (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    title text,
    artist text,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    modified_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    native_title text,
    translated_lyrics text,
    romanized_lyrics text,
    native_lyrics text,
    video_link text,
    snippet_start bigint,
    snippet_end bigint,
    is_placeholder boolean,
    title_language_id bigint,
    native_language_id bigint,
    notes text,
    sources text,
    admin_approved boolean,
    poster_link text,
    UNIQUE(year_id, country_id)
);

CREATE TABLE IF NOT EXISTS song_language (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    song_id bigint REFERENCES song (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    language_id bigint REFERENCES language (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    priority bigint,
    UNIQUE(song_id, language_id),
    UNIQUE(song_id, priority)
);

CREATE TABLE IF NOT EXISTS point_system (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    number bigint
);

CREATE TABLE IF NOT EXISTS point (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    point_system_id bigint REFERENCES point_system (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    place bigint,
    score integer,
    UNIQUE(point_system_id, place)
);

CREATE TABLE IF NOT EXISTS show (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    year_id bigint REFERENCES year (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    point_system_id bigint REFERENCES point_system (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    show_name text COLLATE public.nocase,
    short_name text COLLATE public.nocase,
    voting_opens timestamptz,
    voting_closes timestamptz,
    date date,
    dtf bigint,
    sc bigint,
    special bigint,
    access_type text,
    predictions_close timestamptz,
    UNIQUE(year_id, show_name)
);

CREATE TABLE IF NOT EXISTS song_show (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    song_id bigint REFERENCES song (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    show_id bigint REFERENCES show (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    running_order bigint,
    qualifier_order bigint,
    UNIQUE(song_id, show_id)
);

CREATE TABLE IF NOT EXISTS vote_set (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    voter_id bigint REFERENCES account (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    show_id bigint REFERENCES show (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    country_id text COLLATE public.nocase REFERENCES country (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    nickname text,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    ip_address inet,
    UNIQUE(voter_id, show_id)
);

CREATE TABLE IF NOT EXISTS vote (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    vote_set_id bigint REFERENCES vote_set (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    song_id bigint REFERENCES song (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    score integer,
    UNIQUE(vote_set_id, song_id)
);

CREATE TABLE IF NOT EXISTS api_token (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL REFERENCES account (id) ON DELETE CASCADE,
    token_hash bytea NOT NULL UNIQUE,
    label text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_country_cc3 ON country (cc3);
CREATE INDEX IF NOT EXISTS idx_session_id ON session (session_id);
CREATE INDEX IF NOT EXISTS idx_song_submitter ON song (submitter_id);
CREATE INDEX IF NOT EXISTS idx_song_country ON song (country_id);
CREATE INDEX IF NOT EXISTS idx_song_year ON song (year_id);
CREATE INDEX IF NOT EXISTS idx_song_id_country_id ON song (id, country_id);
CREATE INDEX IF NOT EXISTS idx_vote_set_voter ON vote_set (voter_id);
CREATE INDEX IF NOT EXISTS idx_vote_set_show ON vote_set (show_id);
CREATE INDEX IF NOT EXISTS idx_song_show_song_show ON song_show (song_id, show_id);
CREATE INDEX IF NOT EXISTS idx_point_system_id_score ON point (point_system_id, score DESC);
CREATE INDEX IF NOT EXISTS idx_api_token_user_id ON api_token (user_id);
CREATE INDEX IF NOT EXISTS idx_api_token_hash ON api_token (token_hash);
