BEGIN TRANSACTION;

ALTER TABLE song ADD COLUMN native_title TEXT;
ALTER TABLE song ADD COLUMN translated_lyrics TEXT;
ALTER TABLE song ADD COLUMN romanized_lyrics TEXT;
ALTER TABLE song ADD COLUMN native_lyrics TEXT;
ALTER TABLE song ADD COLUMN video_link TEXT;
ALTER TABLE song ADD COLUMN snippet_start INTEGER;
ALTER TABLE song ADD COLUMN snippet_end INTEGER;
ALTER TABLE song ADD COLUMN is_placeholder INTEGER;

COMMIT;