BEGIN TRANSACTION;
ALTER TABLE user ADD COLUMN email TEXT;
ALTER TABLE user ADD COLUMN password BLOB;
ALTER TABLE user ADD COLUMN salt BLOB;
ALTER TABLE user ADD COLUMN approved INTEGER DEFAULT 0;
ALTER TABLE user ADD COLUMN role TEXT DEFAULT 'user';

CREATE TABLE session (
    id INTEGER PRIMARY KEY,
    user_id INTEGER NOT NULL,
    session_id TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    expires_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES user (id)
);

COMMIT;