BEGIN;

CREATE TABLE custom_playlist (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    owner_id bigint NOT NULL
        REFERENCES account (id) ON UPDATE RESTRICT ON DELETE CASCADE,
    name text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT custom_playlist_name_not_blank CHECK (name ~ '[^[:space:]]'),
    CONSTRAINT custom_playlist_name_length CHECK (char_length(name) <= 100)
);

CREATE TABLE custom_playlist_song (
    playlist_id bigint NOT NULL
        REFERENCES custom_playlist (id) ON UPDATE RESTRICT ON DELETE CASCADE,
    song_id bigint NOT NULL
        REFERENCES song (id) ON UPDATE RESTRICT ON DELETE CASCADE,
    position integer NOT NULL,
    added_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (playlist_id, song_id),
    CONSTRAINT custom_playlist_song_position_check CHECK (position > 0),
    CONSTRAINT custom_playlist_song_position_unique UNIQUE (playlist_id, position)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX custom_playlist_owner_idx ON custom_playlist (owner_id, updated_at DESC, id);
CREATE INDEX custom_playlist_song_song_idx ON custom_playlist_song (song_id, playlist_id);

COMMIT;
