CREATE TABLE artist (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    full_name text NOT NULL CHECK (full_name ~ '[^[:space:]]'),
    native_name text CHECK (native_name IS NULL OR native_name ~ '[^[:space:]]')
);

CREATE INDEX idx_artist_names_ci
    ON artist (LOWER(full_name), LOWER(COALESCE(native_name, '')));

CREATE TABLE artist_credit_set (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE artist_credit (
    artist_credit_set_id bigint NOT NULL
        REFERENCES artist_credit_set (id) ON UPDATE RESTRICT ON DELETE CASCADE,
    position smallint NOT NULL CHECK (position > 0),
    artist_id bigint NOT NULL
        REFERENCES artist (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    stage_name text NOT NULL CHECK (stage_name ~ '[^[:space:]]'),
    join_phrase text,
    PRIMARY KEY (artist_credit_set_id, position),
    CONSTRAINT artist_credit_join_position CHECK (
        (position = 1 AND join_phrase IS NULL)
        OR (position > 1 AND join_phrase ~ '[^[:space:]]')
    )
);

CREATE INDEX idx_artist_credit_artist ON artist_credit (artist_id);

ALTER TABLE song_data ADD COLUMN artist_credit_set_id bigint
    REFERENCES artist_credit_set (id) ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Existing free-form credits cannot be split reliably. Preserve each distinct
-- historical value as one canonical artist; editors can structure collaborations
-- the next time an entry is revised.
INSERT INTO artist (full_name)
SELECT DISTINCT BTRIM(artist)
FROM song_data
WHERE artist ~ '[^[:space:]]';

WITH legacy_artist AS (
    SELECT artist.id AS artist_id, artist.full_name,
           nextval(pg_get_serial_sequence('artist_credit_set', 'id')) AS set_id
    FROM artist
), inserted_sets AS (
    INSERT INTO artist_credit_set (id)
    SELECT set_id FROM legacy_artist
    RETURNING id
)
INSERT INTO artist_credit (
    artist_credit_set_id, position, artist_id, stage_name, join_phrase
)
SELECT legacy_artist.set_id, 1, legacy_artist.artist_id,
       legacy_artist.full_name, NULL
FROM legacy_artist
JOIN inserted_sets ON inserted_sets.id = legacy_artist.set_id;

UPDATE song_data AS data
SET artist_credit_set_id = credit.artist_credit_set_id
FROM artist
JOIN artist_credit AS credit
  ON credit.artist_id = artist.id AND credit.position = 1
WHERE BTRIM(data.artist) = artist.full_name;

COMMENT ON COLUMN song_data.artist IS
    'Deprecated rendered artist credit retained for compatibility; structured credits are canonical.';

CREATE OR REPLACE VIEW current_song AS
SELECT song.id, song.country_id, song.year_id, song.entry_number,
       data.submitter_id, data.title, data.artist, data.created_at, data.changed_by,
       data.modified_at, data.native_title, data.translated_lyrics,
       data.romanized_lyrics, data.native_lyrics, data.video_link,
       data.snippet_start, data.snippet_end, data.snippet2_start,
       data.snippet2_end, COALESCE(status.is_placeholder, false) AS is_placeholder,
       data.title_language_id,
       data.native_language_id, data.language_set_id, data.notes, data.sources,
       COALESCE(status.approval_status, 'pending') AS approval_status,
       status.created_at AS status_created_at,
       data.poster_link, data.vtt_link, data.duration, data.id AS song_data_id,
       song.main_participant, data.genre_set_id, data.key_signature_set_id,
       data.time_signature_set_id, data.artist_credit_set_id
FROM song
JOIN LATERAL (
    SELECT song_data.* FROM song_data
    WHERE song_data.song_id = song.id
       OR (
           song_data.song_id IS NULL
           AND song_data.country_id = song.country_id
           AND song_data.year_id = song.year_id
           AND song_data.entry_number IS NOT DISTINCT FROM song.entry_number
       )
    ORDER BY song_data.created_at DESC, song_data.id DESC
    LIMIT 1
) AS data ON true
LEFT JOIN LATERAL (
    SELECT song_status.approval_status, song_status.is_placeholder,
           song_status.created_at
    FROM song_status
    WHERE song_status.song_id = song.id
    ORDER BY song_status.created_at DESC, song_status.id DESC
    LIMIT 1
) AS status ON true
WHERE data.title IS NOT NULL AND data.artist IS NOT NULL;
