-- Version song genres, key signatures, and time signatures with song_data.
-- The previous song-scoped tables were mutable and therefore could not be
-- represented in the revision-derived audit log.  Like language_set, each
-- unique ordered collection now has one immutable shared set.

CREATE TABLE genre_set (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    subgenre_ids bigint[] NOT NULL UNIQUE,
    CHECK (cardinality(subgenre_ids) > 0)
);

CREATE TABLE genre_set_subgenre (
    genre_set_id bigint NOT NULL REFERENCES genre_set (id) ON DELETE CASCADE,
    subgenre_id bigint NOT NULL REFERENCES subgenre (id) ON DELETE RESTRICT,
    priority smallint NOT NULL,
    PRIMARY KEY (genre_set_id, priority),
    UNIQUE (genre_set_id, subgenre_id)
);

CREATE TABLE key_signature_set (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    signatures jsonb NOT NULL UNIQUE,
    CHECK (jsonb_typeof(signatures) = 'array' AND jsonb_array_length(signatures) > 0)
);

CREATE TABLE key_signature_set_key_signature (
    key_signature_set_id bigint NOT NULL REFERENCES key_signature_set (id) ON DELETE CASCADE,
    priority smallint NOT NULL,
    start_seconds integer NOT NULL CHECK (start_seconds >= 0),
    tonic text,
    mode text,
    microtonal boolean NOT NULL DEFAULT false,
    notes text,
    PRIMARY KEY (key_signature_set_id, priority),
    UNIQUE (key_signature_set_id, start_seconds)
);

CREATE TABLE time_signature_set (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    signatures jsonb NOT NULL UNIQUE,
    CHECK (jsonb_typeof(signatures) = 'array' AND jsonb_array_length(signatures) > 0)
);

CREATE TABLE time_signature_set_time_signature (
    time_signature_set_id bigint NOT NULL REFERENCES time_signature_set (id) ON DELETE CASCADE,
    priority smallint NOT NULL,
    start_seconds integer NOT NULL CHECK (start_seconds >= 0),
    numerator smallint,
    denominator smallint,
    notes text,
    PRIMARY KEY (time_signature_set_id, priority),
    UNIQUE (time_signature_set_id, start_seconds),
    CHECK ((numerator IS NULL) = (denominator IS NULL)),
    CHECK (numerator IS NULL OR numerator > 0),
    CHECK (denominator IS NULL OR denominator IN (1, 2, 4, 8, 16, 32))
);

ALTER TABLE song_data
    ADD COLUMN genre_set_id bigint REFERENCES genre_set (id) ON DELETE RESTRICT,
    ADD COLUMN key_signature_set_id bigint REFERENCES key_signature_set (id) ON DELETE RESTRICT,
    ADD COLUMN time_signature_set_id bigint REFERENCES time_signature_set (id) ON DELETE RESTRICT;

WITH collections AS (
    SELECT song_id,
           ARRAY_AGG(subgenre_id ORDER BY priority NULLS LAST, id)::bigint[] AS values
    FROM song_subgenre GROUP BY song_id
)
INSERT INTO genre_set (subgenre_ids)
SELECT DISTINCT values FROM collections ON CONFLICT DO NOTHING;

INSERT INTO genre_set_subgenre (genre_set_id, subgenre_id, priority)
SELECT sets.id, old.subgenre_id,
       ROW_NUMBER() OVER (
           PARTITION BY old.song_id ORDER BY old.priority NULLS LAST, old.id
       ) - 1
FROM song_subgenre AS old
JOIN LATERAL (
    SELECT ARRAY_AGG(
        member.subgenre_id ORDER BY member.priority NULLS LAST, member.id
    )::bigint[] AS values
    FROM song_subgenre AS member WHERE member.song_id = old.song_id
) AS collection ON true
JOIN genre_set AS sets ON sets.subgenre_ids = collection.values
ON CONFLICT DO NOTHING;

UPDATE song_data AS data
SET genre_set_id = sets.id
FROM (
    SELECT song_id,
           ARRAY_AGG(subgenre_id ORDER BY priority NULLS LAST, id)::bigint[] AS values
    FROM song_subgenre GROUP BY song_id
) AS collection
JOIN genre_set AS sets ON sets.subgenre_ids = collection.values
WHERE data.song_id = collection.song_id;

WITH collections AS (
    SELECT song_id, JSONB_AGG(JSONB_BUILD_OBJECT(
        'start_seconds', start_seconds, 'tonic', tonic, 'mode', mode,
        'microtonal', microtonal, 'notes', notes
    ) ORDER BY start_seconds) AS values
    FROM song_key_signature GROUP BY song_id
)
INSERT INTO key_signature_set (signatures)
SELECT DISTINCT values FROM collections ON CONFLICT DO NOTHING;

INSERT INTO key_signature_set_key_signature (
    key_signature_set_id, priority, start_seconds, tonic, mode, microtonal, notes
)
SELECT sets.id, ROW_NUMBER() OVER (PARTITION BY old.song_id ORDER BY old.start_seconds) - 1,
       old.start_seconds, old.tonic, old.mode, old.microtonal, old.notes
FROM song_key_signature AS old
JOIN LATERAL (
    SELECT JSONB_AGG(JSONB_BUILD_OBJECT(
        'start_seconds', member.start_seconds, 'tonic', member.tonic,
        'mode', member.mode, 'microtonal', member.microtonal, 'notes', member.notes
    ) ORDER BY member.start_seconds) AS values
    FROM song_key_signature AS member WHERE member.song_id = old.song_id
) AS collection ON true
JOIN key_signature_set AS sets ON sets.signatures = collection.values
ON CONFLICT DO NOTHING;

UPDATE song_data AS data
SET key_signature_set_id = sets.id
FROM (
    SELECT song_id, JSONB_AGG(JSONB_BUILD_OBJECT(
        'start_seconds', start_seconds, 'tonic', tonic, 'mode', mode,
        'microtonal', microtonal, 'notes', notes
    ) ORDER BY start_seconds) AS values
    FROM song_key_signature GROUP BY song_id
) AS collection
JOIN key_signature_set AS sets ON sets.signatures = collection.values
WHERE data.song_id = collection.song_id;

WITH collections AS (
    SELECT song_id, JSONB_AGG(JSONB_BUILD_OBJECT(
        'start_seconds', start_seconds, 'numerator', numerator,
        'denominator', denominator, 'notes', notes
    ) ORDER BY start_seconds) AS values
    FROM song_time_signature GROUP BY song_id
)
INSERT INTO time_signature_set (signatures)
SELECT DISTINCT values FROM collections ON CONFLICT DO NOTHING;

INSERT INTO time_signature_set_time_signature (
    time_signature_set_id, priority, start_seconds, numerator, denominator, notes
)
SELECT sets.id, ROW_NUMBER() OVER (PARTITION BY old.song_id ORDER BY old.start_seconds) - 1,
       old.start_seconds, old.numerator, old.denominator, old.notes
FROM song_time_signature AS old
JOIN LATERAL (
    SELECT JSONB_AGG(JSONB_BUILD_OBJECT(
        'start_seconds', member.start_seconds, 'numerator', member.numerator,
        'denominator', member.denominator, 'notes', member.notes
    ) ORDER BY member.start_seconds) AS values
    FROM song_time_signature AS member WHERE member.song_id = old.song_id
) AS collection ON true
JOIN time_signature_set AS sets ON sets.signatures = collection.values
ON CONFLICT DO NOTHING;

UPDATE song_data AS data
SET time_signature_set_id = sets.id
FROM (
    SELECT song_id, JSONB_AGG(JSONB_BUILD_OBJECT(
        'start_seconds', start_seconds, 'numerator', numerator,
        'denominator', denominator, 'notes', notes
    ) ORDER BY start_seconds) AS values
    FROM song_time_signature GROUP BY song_id
) AS collection
JOIN time_signature_set AS sets ON sets.signatures = collection.values
WHERE data.song_id = collection.song_id;

DROP TABLE song_subgenre;
DROP TABLE song_key_signature;
DROP TABLE song_time_signature;

CREATE INDEX idx_song_data_genre_set ON song_data (genre_set_id);
CREATE INDEX idx_song_data_key_signature_set ON song_data (key_signature_set_id);
CREATE INDEX idx_song_data_time_signature_set ON song_data (time_signature_set_id);

CREATE OR REPLACE VIEW current_song AS
SELECT song.id, song.country_id, song.year_id, song.entry_number,
       data.submitter_id, data.title, data.artist, data.created_at, data.changed_by,
       data.modified_at, data.native_title, data.translated_lyrics,
       data.romanized_lyrics, data.native_lyrics, data.video_link,
       data.snippet_start, data.snippet_end, data.snippet2_start,
       data.snippet2_end, COALESCE(status.is_placeholder, false) AS is_placeholder,
       data.title_language_id,
       data.native_language_id, data.language_set_id, data.notes, data.sources,
       COALESCE(status.approval_status, 'pending') AS approval_status,
       status.created_at AS status_created_at,
       data.poster_link, data.vtt_link, data.duration, data.id AS song_data_id,
       song.main_participant, data.genre_set_id, data.key_signature_set_id,
       data.time_signature_set_id
FROM song
JOIN LATERAL (
    SELECT song_data.* FROM song_data
    WHERE song_data.song_id = song.id
       OR (
           song_data.song_id IS NULL
           AND song_data.country_id = song.country_id
           AND song_data.year_id = song.year_id
           AND song_data.entry_number IS NOT DISTINCT FROM song.entry_number
       )
    ORDER BY song_data.created_at DESC, song_data.id DESC
    LIMIT 1
) AS data ON true
LEFT JOIN LATERAL (
    SELECT song_status.approval_status, song_status.is_placeholder,
           song_status.created_at
    FROM song_status
    WHERE song_status.song_id = song.id
    ORDER BY song_status.created_at DESC, song_status.id DESC
    LIMIT 1
) AS status ON true
WHERE data.title IS NOT NULL AND data.artist IS NOT NULL;
