BEGIN;

-- Per-user linked scrobbling accounts (Last.fm / Libre.fm). One row per
-- (user, service); session_key is the long-lived AudioScrobbler session
-- key obtained via the web-auth flow. `enabled` lets a user pause
-- scrobbling without unlinking.
CREATE TABLE IF NOT EXISTS scrobble_account (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL REFERENCES account (id) ON DELETE CASCADE,
    service text NOT NULL,
    session_key text NOT NULL,
    remote_username text,
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_scrobbled_at timestamptz,
    UNIQUE (user_id, service)
);

CREATE INDEX IF NOT EXISTS idx_scrobble_account_user_id ON scrobble_account (user_id);

COMMIT;
