CREATE EXTENSION IF NOT EXISTS unaccent;

CREATE TABLE song_approval_status (
    name text PRIMARY KEY
);

ALTER TABLE conversation
    ADD COLUMN metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    ADD CONSTRAINT conversation_metadata_object_check
        CHECK (jsonb_typeof(metadata) = 'object');

CREATE INDEX conversation_banner_idx
    ON conversation (id) WHERE metadata @> '{"banner": true}'::jsonb;

INSERT INTO song_approval_status (name) VALUES
    ('pending'), ('accepted'), ('rejected'), ('more-info');

CREATE TABLE language_set (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    language_ids bigint[] NOT NULL UNIQUE,
    CHECK (cardinality(language_ids) > 0)
);

CREATE TABLE language_set_language (
    language_set_id bigint NOT NULL
        REFERENCES language_set (id) ON UPDATE RESTRICT ON DELETE CASCADE,
    language_id bigint NOT NULL
        REFERENCES language (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    priority smallint NOT NULL,
    PRIMARY KEY (language_set_id, priority),
    UNIQUE (language_set_id, language_id)
);

INSERT INTO language_set (language_ids)
SELECT array_agg(language_id ORDER BY priority)
FROM song_language
GROUP BY song_id
ON CONFLICT (language_ids) DO NOTHING;

INSERT INTO language_set_language (language_set_id, language_id, priority)
SELECT language_set.id, member.language_id, (member.ordinality - 1)::smallint
FROM language_set
CROSS JOIN LATERAL unnest(language_set.language_ids)
    WITH ORDINALITY AS member(language_id, ordinality);

ALTER TABLE song
    ALTER COLUMN country_id SET NOT NULL,
    ALTER COLUMN year_id SET NOT NULL,
    ALTER COLUMN entry_number DROP NOT NULL;

CREATE TABLE song_data (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    song_id bigint REFERENCES song (id) ON UPDATE RESTRICT ON DELETE SET NULL,
    country_id text NOT NULL
        REFERENCES country (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    year_id bigint NOT NULL
        REFERENCES year (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    entry_number integer,
    language_set_id bigint
        REFERENCES language_set (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    submitter_id bigint
        REFERENCES account (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    title text,
    artist text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    native_title text,
    translated_lyrics text,
    romanized_lyrics text,
    native_lyrics text,
    video_link text,
    snippet_start integer,
    snippet_end integer,
    snippet2_start integer,
    snippet2_end integer,
    title_language_id bigint,
    native_language_id bigint,
    notes text,
    sources text,
    changed_by bigint DEFAULT NULLIF(
        current_setting('app.current_user_id', true), ''
    )::bigint REFERENCES account (id) ON UPDATE RESTRICT ON DELETE SET NULL,
    poster_link text,
    vtt_link text,
    duration double precision,
    CONSTRAINT song_data_snippet2_max_duration CHECK (
        snippet2_start IS NULL
        OR snippet2_end IS NULL
        OR snippet2_end - snippet2_start <= 10
    )
);

WITH ordered_languages AS (
    SELECT song_id, array_agg(language_id ORDER BY priority) AS language_ids
    FROM song_language
    GROUP BY song_id
)
INSERT INTO song_data (
    song_id, country_id, year_id, entry_number, language_set_id,
    submitter_id, title, artist, created_at, modified_at, native_title,
    translated_lyrics, romanized_lyrics, native_lyrics, video_link,
    snippet_start, snippet_end, snippet2_start, snippet2_end,
    title_language_id, native_language_id, notes, sources, changed_by,
    poster_link, vtt_link, duration
)
SELECT song.id, song.country_id, song.year_id, song.entry_number,
       language_set.id, song.submitter_id, song.title, song.artist,
       song.created_at, COALESCE(song.modified_at, song.created_at, CURRENT_TIMESTAMP),
       song.native_title,
       song.translated_lyrics, song.romanized_lyrics, song.native_lyrics,
       song.video_link, song.snippet_start, song.snippet_end,
       song.snippet2_start, song.snippet2_end,
       song.title_language_id, song.native_language_id, song.notes,
       song.sources, initial_change.changed_by,
       song.poster_link, song.vtt_link, song.duration
FROM song
JOIN year ON year.id = song.year_id
LEFT JOIN LATERAL (
    SELECT audit.changed_by
    FROM song_audit_log AS audit
    WHERE audit.song_id = song.id AND audit.event_type = 'create'
    ORDER BY audit.changed_at, audit.id
    LIMIT 1
) AS initial_change ON true
LEFT JOIN ordered_languages ON ordered_languages.song_id = song.id
LEFT JOIN language_set
    ON language_set.language_ids = ordered_languages.language_ids;

-- Rebuild immutable metadata history from the legacy audit stream. The old
-- trigger could emit several audit rows for a single UPDATE, so replay them
-- in audit-id order to retain each visible event as its own revision.
-- BEGIN LEGACY SONG AUDIT RECONSTRUCTION
CREATE FUNCTION insert_reconstructed_song_data(
    state jsonb,
    stable_song_id bigint,
    stable_entry_number integer,
    revision_at timestamptz,
    revision_by bigint,
    is_deletion boolean DEFAULT false
)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
    IF is_deletion THEN
        INSERT INTO song_data (
            song_id, country_id, year_id, entry_number,
            created_at, modified_at, changed_by
        ) VALUES (
            NULL, state ->> 'country_id', (state ->> 'year_id')::bigint,
            stable_entry_number, revision_at, NULL, revision_by
        );
        RETURN;
    END IF;

    INSERT INTO song_data (
        song_id, country_id, year_id, entry_number, language_set_id,
        submitter_id, title, artist, created_at, modified_at, native_title,
        translated_lyrics, romanized_lyrics, native_lyrics, video_link,
        snippet_start, snippet_end, snippet2_start, snippet2_end,
        title_language_id, native_language_id, notes,
        sources, changed_by, poster_link, vtt_link, duration
    ) VALUES (
        stable_song_id, state ->> 'country_id',
        (state ->> 'year_id')::bigint, stable_entry_number,
        (state ->> 'language_set_id')::bigint,
        (state ->> 'submitter_id')::bigint,
        state ->> 'title', state ->> 'artist', revision_at, revision_at,
        state ->> 'native_title', state ->> 'translated_lyrics',
        state ->> 'romanized_lyrics', state ->> 'native_lyrics',
        state ->> 'video_link', (state ->> 'snippet_start')::integer,
        (state ->> 'snippet_end')::integer,
        (state ->> 'snippet2_start')::integer,
        (state ->> 'snippet2_end')::integer,
        (state ->> 'title_language_id')::bigint,
        (state ->> 'native_language_id')::bigint,
        state ->> 'notes', state ->> 'sources', revision_by,
        state ->> 'poster_link', state ->> 'vtt_link',
        (state ->> 'duration')::double precision
    );
END;
$$;

DO $$
DECLARE
    legacy record;
    revision record;
    audit record;
    changed_field record;
    seed song_data%ROWTYPE;
    latest_audit record;
    first_audit_at timestamptz;
    state jsonb;
    stable_song_id bigint;
    stable_entry_number integer;
    has_seed boolean;
    has_create boolean;
    revision_by bigint;
    is_deletion boolean;
    has_data_change boolean;
BEGIN
    FOR legacy IN
        SELECT DISTINCT song_id
        FROM song_audit_log
        WHERE song_id IS NOT NULL
        ORDER BY song_id
    LOOP
        SELECT * INTO seed
        FROM song_data
        WHERE song_id = legacy.song_id
        ORDER BY created_at DESC, id DESC
        LIMIT 1;
        has_seed := FOUND;

        SELECT * INTO latest_audit
        FROM song_audit_log
        WHERE song_id = legacy.song_id
        ORDER BY changed_at DESC, id DESC
        LIMIT 1;

        IF has_seed THEN
            state := TO_JSONB(seed);
            stable_song_id := seed.song_id;
            stable_entry_number := seed.entry_number;
        ELSE
            state := JSONB_BUILD_OBJECT(
                'song_id', NULL,
                'country_id', latest_audit.song_country_id,
                'year_id', latest_audit.song_year_id,
                'entry_number', 1,
                'title', latest_audit.song_title,
                'artist', latest_audit.song_artist
            );
            stable_song_id := NULL;
            stable_entry_number := 1;
        END IF;

        -- Walk backwards to recover the state before the first logged event.
        FOR audit IN
            SELECT *
            FROM song_audit_log
            WHERE song_id = legacy.song_id
            ORDER BY changed_at DESC, id DESC
        LOOP
            FOR changed_field IN
                SELECT field.key, field.value
                FROM JSONB_EACH(COALESCE(audit.changed_fields, '{}'::jsonb)) AS field
                WHERE field.key = ANY (ARRAY[
                    'language_set_id', 'submitter_id', 'title', 'artist',
                    'native_title', 'translated_lyrics', 'romanized_lyrics',
                    'native_lyrics', 'video_link', 'snippet_start',
                    'snippet_end', 'snippet2_start', 'snippet2_end',
                    'title_language_id',
                    'native_language_id', 'notes', 'sources', 'poster_link',
                    'vtt_link', 'duration', 'country_id', 'year_id'
                ])
            LOOP
                state := JSONB_SET(
                    state,
                    ARRAY[changed_field.key],
                    COALESCE(changed_field.value -> 'old', 'null'::jsonb),
                    true
                );
            END LOOP;
        END LOOP;

        SELECT MIN(changed_at), BOOL_OR(event_type = 'create')
        INTO first_audit_at, has_create
        FROM song_audit_log
        WHERE song_id = legacy.song_id;

        IF has_seed THEN
            DELETE FROM song_data WHERE id = seed.id;
        END IF;

        -- Songs predating the audit trigger need a baseline revision before
        -- their first recorded change.
        IF NOT has_create THEN
            PERFORM insert_reconstructed_song_data(
                state,
                stable_song_id,
                stable_entry_number,
                CASE WHEN has_seed THEN LEAST(seed.created_at, first_audit_at)
                     ELSE first_audit_at - INTERVAL '1 microsecond' END,
                NULL
            );
        END IF;

        -- Replay the audit stream forwards. Rows sharing a timestamp came
        -- from one legacy UPDATE and become one immutable revision.
        FOR revision IN
            SELECT DISTINCT changed_at
            FROM song_audit_log
            WHERE song_id = legacy.song_id
            ORDER BY changed_at
        LOOP
            revision_by := NULL;
            is_deletion := false;
            has_data_change := false;

            FOR audit IN
                SELECT *
                FROM song_audit_log
                WHERE song_id = legacy.song_id
                  AND changed_at = revision.changed_at
                ORDER BY id
            LOOP
                revision_by := COALESCE(revision_by, audit.changed_by);
                is_deletion := is_deletion OR audit.event_type = 'delete';
                has_data_change := has_data_change
                    OR audit.event_type NOT IN ('placeholder_on', 'placeholder_off');

                FOR changed_field IN
                    SELECT field.key, field.value
                    FROM JSONB_EACH(
                        COALESCE(audit.changed_fields, '{}'::jsonb)
                    ) AS field
                    WHERE field.key = ANY (ARRAY[
                        'language_set_id', 'submitter_id', 'title', 'artist',
                        'native_title', 'translated_lyrics',
                        'romanized_lyrics', 'native_lyrics', 'video_link',
                        'snippet_start', 'snippet_end', 'snippet2_start',
                        'snippet2_end',
                        'title_language_id', 'native_language_id', 'notes',
                        'sources', 'poster_link', 'vtt_link', 'duration',
                        'country_id', 'year_id'
                    ])
                LOOP
                    state := JSONB_SET(
                        state,
                        ARRAY[changed_field.key],
                        COALESCE(changed_field.value -> 'new', 'null'::jsonb),
                        true
                    );
                END LOOP;
                state := JSONB_SET(
                    JSONB_SET(
                        JSONB_SET(
                            JSONB_SET(
                                state, '{title}',
                                COALESCE(
                                    TO_JSONB(audit.song_title), 'null'::jsonb
                                ), true
                            ),
                            '{artist}',
                            COALESCE(
                                TO_JSONB(audit.song_artist), 'null'::jsonb
                            ), true
                        ),
                        '{country_id}',
                        COALESCE(
                            TO_JSONB(audit.song_country_id), 'null'::jsonb
                        ), true
                    ),
                    '{year_id}',
                    COALESCE(TO_JSONB(audit.song_year_id), 'null'::jsonb), true
                );
            END LOOP;

            IF has_data_change THEN
                PERFORM insert_reconstructed_song_data(
                    state, stable_song_id, stable_entry_number,
                    revision.changed_at, revision_by, is_deletion
                );
            END IF;
        END LOOP;
    END LOOP;
END;
$$;

DROP FUNCTION insert_reconstructed_song_data(
    jsonb, bigint, integer, timestamptz, bigint, boolean
);
-- END LEGACY SONG AUDIT RECONSTRUCTION

CREATE INDEX idx_song_data_song_created
    ON song_data (song_id, created_at DESC, id DESC);
CREATE INDEX idx_song_data_entry_created
    ON song_data (country_id, year_id, entry_number, created_at DESC, id DESC);
CREATE INDEX idx_song_data_language_set ON song_data (language_set_id);
CREATE INDEX idx_song_data_submitter ON song_data (submitter_id);
CREATE INDEX idx_language_set_language_language_id
    ON language_set_language (language_id);

CREATE TABLE song_status (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    song_id bigint NOT NULL
        REFERENCES song (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    song_data_id bigint NOT NULL
        REFERENCES song_data (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    approval_status text NOT NULL DEFAULT 'pending'
        REFERENCES song_approval_status (name)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    is_placeholder boolean NOT NULL DEFAULT false,
    changed_by bigint
        REFERENCES account (id) ON UPDATE RESTRICT ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_song_status_song_created
    ON song_status (song_id, created_at DESC, id DESC);

WITH initial_state AS (
    SELECT song.id AS song_id,
           data.id AS song_data_id,
           data.created_at,
           CASE WHEN year.status IN ('closed', 'ongoing')
                THEN 'accepted' ELSE 'pending' END AS approval_status,
           COALESCE((
               SELECT CASE audit.event_type
                          WHEN 'placeholder_on' THEN false
                          WHEN 'placeholder_off' THEN true
                      END
               FROM song_audit_log AS audit
               WHERE audit.song_id = song.id
                 AND audit.event_type IN ('placeholder_on', 'placeholder_off')
               ORDER BY audit.changed_at, audit.id
               LIMIT 1
           ), song.is_placeholder, false) AS is_placeholder
    FROM song
    JOIN year ON year.id = song.year_id
    JOIN LATERAL (
        SELECT revision.id, revision.created_at
        FROM song_data AS revision
        WHERE revision.song_id = song.id
        ORDER BY revision.created_at, revision.id
        LIMIT 1
    ) AS data ON true
)
INSERT INTO song_status (
    song_id, song_data_id, approval_status, is_placeholder, created_at
)
SELECT song_id, song_data_id, approval_status, is_placeholder, created_at
FROM initial_state;

INSERT INTO song_status (
    song_id, song_data_id, approval_status, is_placeholder,
    changed_by, created_at
)
SELECT song.id,
       context.id,
       CASE WHEN year.status IN ('closed', 'ongoing')
            THEN 'accepted' ELSE 'pending' END,
       audit.event_type = 'placeholder_on',
       audit.changed_by,
       audit.changed_at
FROM song_audit_log AS audit
JOIN song ON song.id = audit.song_id
JOIN year ON year.id = song.year_id
JOIN LATERAL (
    SELECT revision.id
    FROM song_data AS revision
    WHERE revision.song_id = song.id
      AND revision.created_at <= audit.changed_at
    ORDER BY revision.created_at DESC, revision.id DESC
    LIMIT 1
) AS context ON true
WHERE audit.event_type IN ('placeholder_on', 'placeholder_off')
ORDER BY audit.changed_at, audit.id;

CREATE TABLE song_verification_comment (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    song_data_id bigint NOT NULL
        REFERENCES song_data (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    author_id bigint NOT NULL
        REFERENCES account (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    body text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT song_verification_comment_body_not_blank
        CHECK (body ~ '[^[:space:]]'),
    CONSTRAINT song_verification_comment_body_length
        CHECK (char_length(body) <= 2000)
);

CREATE INDEX idx_song_verification_comment_data_created
    ON song_verification_comment (song_data_id, created_at, id);

CREATE VIEW current_song AS
SELECT song.id, song.country_id, song.year_id, song.entry_number,
       data.submitter_id, data.title, data.artist, data.created_at, data.changed_by,
       data.modified_at, data.native_title, data.translated_lyrics,
       data.romanized_lyrics, data.native_lyrics, data.video_link,
       data.snippet_start, data.snippet_end, data.snippet2_start,
       data.snippet2_end, COALESCE(status.is_placeholder, false) AS is_placeholder,
       data.title_language_id,
       data.native_language_id, data.language_set_id, data.notes, data.sources,
       COALESCE(status.approval_status, 'pending') AS approval_status,
       status.created_at AS status_created_at,
       data.poster_link, data.vtt_link, data.duration, data.id AS song_data_id
FROM song
JOIN LATERAL (
    SELECT song_data.*
    FROM song_data
    WHERE song_data.country_id = song.country_id
      AND song_data.year_id = song.year_id
      AND song_data.entry_number IS NOT DISTINCT FROM song.entry_number
    ORDER BY song_data.created_at DESC, song_data.id DESC
    LIMIT 1
) AS data ON true
LEFT JOIN LATERAL (
    SELECT song_status.approval_status, song_status.is_placeholder,
           song_status.created_at
    FROM song_status
    WHERE song_status.song_id = song.id
    ORDER BY song_status.created_at DESC, song_status.id DESC
    LIMIT 1
) AS status ON true
WHERE data.title IS NOT NULL AND data.artist IS NOT NULL;

DROP TRIGGER IF EXISTS song_audit ON song;
DROP FUNCTION IF EXISTS song_audit_trigger();
DROP TRIGGER IF EXISTS trg_queue_analytics_on_song ON song;

-- Preserve the public stored-function signatures while moving their metadata
-- reads to the latest song revision.
DO $$
DECLARE
    function_definition text;
BEGIN
    FOR function_definition IN
        SELECT pg_get_functiondef(routine.oid)
        FROM pg_proc AS routine
        JOIN pg_namespace AS namespace ON namespace.oid = routine.pronamespace
        WHERE namespace.nspname = 'public'
          AND routine.prokind = 'f'
          AND (
              pg_get_functiondef(routine.oid) LIKE '%FROM song %'
              OR pg_get_functiondef(routine.oid) LIKE '%JOIN song %'
              OR pg_get_functiondef(routine.oid) LIKE E'%FROM song\n%'
              OR pg_get_functiondef(routine.oid) LIKE E'%JOIN song\n%'
          )
    LOOP
        function_definition := replace(
            function_definition,
            E'FROM song\n',
            E'FROM current_song AS song\n'
        );
        function_definition := replace(
            function_definition, 'FROM song ', 'FROM current_song '
        );
        function_definition := replace(
            function_definition,
            'JOIN song ON',
            'JOIN current_song AS song ON'
        );
        function_definition := replace(
            function_definition, 'JOIN song ', 'JOIN current_song '
        );
        EXECUTE function_definition;
    END LOOP;
END;
$$;

DROP TABLE song_language;

ALTER TABLE song
    DROP COLUMN submitter_id,
    DROP COLUMN title,
    DROP COLUMN artist,
    DROP COLUMN created_at,
    DROP COLUMN modified_at,
    DROP COLUMN native_title,
    DROP COLUMN translated_lyrics,
    DROP COLUMN romanized_lyrics,
    DROP COLUMN native_lyrics,
    DROP COLUMN video_link,
    DROP COLUMN snippet_start,
    DROP COLUMN snippet_end,
    DROP COLUMN snippet2_start,
    DROP COLUMN snippet2_end,
    DROP COLUMN is_placeholder,
    DROP COLUMN title_language_id,
    DROP COLUMN native_language_id,
    DROP COLUMN notes,
    DROP COLUMN sources,
    DROP COLUMN admin_approved,
    DROP COLUMN poster_link,
    DROP COLUMN vtt_link,
    DROP COLUMN duration;

CREATE FUNCTION set_song_data_entry_tuple()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.song_id IS NOT NULL THEN
        SELECT country_id, year_id, entry_number
        INTO NEW.country_id, NEW.year_id, NEW.entry_number
        FROM song
        WHERE id = NEW.song_id;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER set_song_data_entry_tuple
BEFORE INSERT ON song_data
FOR EACH ROW EXECUTE FUNCTION set_song_data_entry_tuple();

CREATE FUNCTION sync_song_data_entry_tuple()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    UPDATE song_data
    SET country_id = NEW.country_id,
        year_id = NEW.year_id,
        entry_number = NEW.entry_number
    WHERE song_id = NEW.id;
    RETURN NEW;
END;
$$;

CREATE TRIGGER sync_song_data_entry_tuple
AFTER UPDATE OF country_id, year_id, entry_number ON song
FOR EACH ROW EXECUTE FUNCTION sync_song_data_entry_tuple();

DROP TABLE song_audit_log;

CREATE VIEW song_change AS
WITH ordered AS (
    SELECT data.*,
           ROW_NUMBER() OVER entry_history AS revision_number,
           TO_JSONB(data) AS current_row,
           LAG(TO_JSONB(data)) OVER entry_history AS previous_row
    FROM song_data AS data
    WINDOW entry_history AS (
        PARTITION BY country_id, year_id, entry_number
        ORDER BY created_at, id
    )
), compared AS (
    SELECT ordered.*,
           current_row - ARRAY[
               'id', 'song_id', 'country_id', 'year_id', 'entry_number',
               'created_at', 'modified_at', 'changed_by'
           ] AS current_values,
           previous_row - ARRAY[
               'id', 'song_id', 'country_id', 'year_id', 'entry_number',
               'created_at', 'modified_at', 'changed_by'
           ] AS previous_values
    FROM ordered
)
SELECT compared.id,
       CASE
           WHEN revision_number = 1 THEN 'create'
           WHEN (previous_row ->> 'title' IS NULL
                  OR previous_row ->> 'artist' IS NULL)
             AND title IS NOT NULL AND artist IS NOT NULL THEN 'create'
           WHEN title IS NULL OR artist IS NULL THEN 'delete'
           WHEN LOWER(previous_row ->> 'title')
                    IS DISTINCT FROM LOWER(title)
             OR LOWER(previous_row ->> 'artist')
                    IS DISTINCT FROM LOWER(artist)
               THEN 'song_replacement'
           WHEN (previous_row ->> 'submitter_id')
                    IS DISTINCT FROM submitter_id::text
               THEN 'ownership_change'
           ELSE 'song_modification'
       END AS event_type,
       changed_by,
       created_at AS changed_at,
       COALESCE(song_id, (previous_row ->> 'song_id')::bigint) AS song_id,
       CASE WHEN title IS NULL OR artist IS NULL
            THEN previous_row ->> 'title' ELSE title END AS song_title,
       CASE WHEN title IS NULL OR artist IS NULL
            THEN previous_row ->> 'artist' ELSE artist END AS song_artist,
       country_id AS song_country_id,
       year_id AS song_year_id,
       CASE WHEN revision_number = 1 OR title IS NULL OR artist IS NULL
            THEN NULL ELSE fields.changed_fields END AS changed_fields
FROM compared
LEFT JOIN LATERAL (
    SELECT JSONB_OBJECT_AGG(
               field.key,
               JSONB_BUILD_OBJECT(
                   'old', previous_values -> field.key,
                   'new', current_values -> field.key
               )
           ) AS changed_fields
    FROM JSONB_EACH(current_values) AS field
    WHERE previous_values -> field.key IS DISTINCT FROM field.value
) AS fields ON true;

CREATE TRIGGER trg_queue_analytics_on_song
AFTER UPDATE OF country_id ON song
FOR EACH ROW
WHEN (OLD.country_id IS DISTINCT FROM NEW.country_id)
EXECUTE FUNCTION trigger_queue_analytics_from_song();

CREATE FUNCTION trigger_queue_analytics_from_song_data()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    show_id_to_refresh bigint;
BEGIN
    FOR show_id_to_refresh IN
        SELECT show_id FROM song_show WHERE song_id = NEW.song_id
    LOOP
        PERFORM queue_analytics_show_refresh(show_id_to_refresh, 'official');
    END LOOP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_queue_analytics_on_song_data
AFTER INSERT ON song_data
FOR EACH ROW EXECUTE FUNCTION trigger_queue_analytics_from_song_data();
