BEGIN;

-- Two-level genre taxonomy for songs. ``genre`` holds the broad
-- category (Rock, Pop, …); ``subgenre`` holds a more specific tag with
-- a parent genre. Whenever a new genre is created, the application
-- mirrors it as a subgenre under itself (so "Rock" is both a genre and
-- a Rock-flavoured subgenre), letting submitters pick a subgenre even
-- when no specialised one applies.

CREATE TABLE IF NOT EXISTS genre (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS subgenre (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    genre_id bigint NOT NULL REFERENCES genre (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    name text NOT NULL,
    UNIQUE (genre_id, name)
);

CREATE INDEX IF NOT EXISTS subgenre_genre_idx ON subgenre (genre_id);

COMMIT;
