BEGIN;

-- Songs to subgenres, many-to-many with priority. Mirrors
-- song_language: each song carries an ordered list of subgenres,
-- starting with the most representative one.

CREATE TABLE IF NOT EXISTS song_subgenre (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    song_id bigint NOT NULL REFERENCES song (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    subgenre_id bigint NOT NULL REFERENCES subgenre (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    priority smallint,
    UNIQUE (song_id, subgenre_id),
    UNIQUE (song_id, priority)
);

CREATE INDEX IF NOT EXISTS song_subgenre_song_idx ON song_subgenre (song_id);

COMMIT;
