BEGIN;

CREATE TABLE national_final_status (
    name text PRIMARY KEY
);

INSERT INTO national_final_status (name) VALUES
    ('draft'),
    ('submissions'),
    ('voting'),
    ('finished'),
    ('cancelled');

CREATE TABLE national_final (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    year_id bigint NOT NULL
        REFERENCES year (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    owner_id bigint NOT NULL
        REFERENCES account (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    owner_country_id text
        REFERENCES country (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    short_name text NOT NULL,
    name text NOT NULL,
    status text NOT NULL DEFAULT 'draft'
        REFERENCES national_final_status (name) ON UPDATE RESTRICT ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT national_final_short_name_check
        CHECK (short_name ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    CONSTRAINT national_final_name_not_blank CHECK (name ~ '[^[:space:]]'),
    UNIQUE (year_id, short_name)
);

ALTER TABLE show
    ADD COLUMN national_final_id bigint
        REFERENCES national_final (id) ON UPDATE RESTRICT ON DELETE RESTRICT;

DO $$
DECLARE
    object_name text;
BEGIN
    FOR object_name IN
        SELECT conname FROM pg_constraint
        WHERE conrelid = 'show'::regclass AND contype = 'u'
          AND pg_get_constraintdef(oid) IN (
              'UNIQUE (year_id, show_name)',
              'UNIQUE (year_id, short_name)'
          )
    LOOP
        EXECUTE format('ALTER TABLE show DROP CONSTRAINT %I', object_name);
    END LOOP;
    FOR object_name IN
        SELECT indexrelid::regclass::text FROM pg_index
        WHERE indrelid = 'show'::regclass AND indisunique
          AND (
              pg_get_indexdef(indexrelid) LIKE '%(year_id, show_name)%'
              OR pg_get_indexdef(indexrelid) LIKE '%(year_id, short_name)%'
          )
    LOOP
        EXECUTE format('DROP INDEX IF EXISTS %s', object_name);
    END LOOP;
END
$$;

ALTER TABLE song
    ADD COLUMN main_participant boolean NOT NULL DEFAULT true;

CREATE OR REPLACE VIEW current_song AS
SELECT song.id, song.country_id, song.year_id, song.entry_number,
       data.submitter_id, data.title, data.artist, data.created_at, data.changed_by,
       data.modified_at, data.native_title, data.translated_lyrics,
       data.romanized_lyrics, data.native_lyrics, data.video_link,
       data.snippet_start, data.snippet_end, data.snippet2_start,
       data.snippet2_end, COALESCE(status.is_placeholder, false) AS is_placeholder,
       data.title_language_id, data.native_language_id, data.language_set_id,
       data.notes, data.sources,
       COALESCE(status.approval_status, 'pending') AS approval_status,
       status.created_at AS status_created_at, data.poster_link, data.vtt_link,
       data.duration, data.id AS song_data_id, song.main_participant
FROM song
JOIN LATERAL (
    SELECT song_data.* FROM song_data
    WHERE song_data.song_id = song.id
       OR (song_data.song_id IS NULL
           AND song_data.country_id = song.country_id
           AND song_data.year_id = song.year_id
           AND song_data.entry_number IS NOT DISTINCT FROM song.entry_number)
    ORDER BY song_data.created_at DESC, song_data.id DESC
    LIMIT 1
) AS data ON true
LEFT JOIN LATERAL (
    SELECT song_status.approval_status, song_status.is_placeholder,
           song_status.created_at
    FROM song_status
    WHERE song_status.song_id = song.id
    ORDER BY song_status.created_at DESC, song_status.id DESC
    LIMIT 1
) AS status ON true
WHERE data.title IS NOT NULL AND data.artist IS NOT NULL;

CREATE TABLE national_final_song (
    national_final_id bigint NOT NULL
        REFERENCES national_final (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    song_id bigint NOT NULL
        REFERENCES song (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (national_final_id, song_id)
);

CREATE INDEX national_final_owner_idx ON national_final (owner_id);
CREATE UNIQUE INDEX national_final_year_country_unique
    ON national_final (year_id, owner_country_id)
    WHERE owner_country_id IS NOT NULL AND status <> 'cancelled';
CREATE INDEX national_final_song_song_idx ON national_final_song (song_id);
CREATE INDEX show_national_final_idx ON show (national_final_id);

CREATE TABLE show_types (
    id text PRIMARY KEY,
    name text NOT NULL UNIQUE,
    sort_order smallint NOT NULL UNIQUE
);

INSERT INTO show_types (id, name, sort_order) VALUES
    ('sf', 'Semi-Final', 1),
    ('sc', 'Repechage', 2),
    ('f', 'Final', 3);

ALTER TABLE show
    ADD COLUMN show_type text REFERENCES show_types (id),
    ADD COLUMN show_number smallint;

UPDATE show
SET show_type = regexp_replace(short_name, '[0-9]+$', ''),
    show_number = NULLIF(regexp_replace(short_name, '\D', '', 'g'), '')::smallint;

ALTER TABLE show
    ALTER COLUMN show_type SET NOT NULL,
    ADD CONSTRAINT show_number_check CHECK (
        show_number IS NULL OR (show_type = 'sf' AND show_number > 0)
    );

ALTER TABLE show
    DROP COLUMN show_name,
    DROP COLUMN short_name,
    ADD COLUMN short_name text GENERATED ALWAYS AS (
        show_type || COALESCE(show_number::text, '')
    ) STORED,
    ADD COLUMN show_name text GENERATED ALWAYS AS (
        CASE show_type
            WHEN 'f' THEN 'Final'
            WHEN 'sf' THEN 'Semi-Final'
            WHEN 'sc' THEN 'Repechage'
        END || COALESCE(' ' || show_number::text, '')
    ) STORED;

CREATE UNIQUE INDEX show_main_short_name_unique
    ON show (year_id, short_name)
    WHERE national_final_id IS NULL;

CREATE UNIQUE INDEX show_national_final_short_name_unique
    ON show (national_final_id, short_name)
    WHERE national_final_id IS NOT NULL;

UPDATE country_show_results
SET show_name = 'Repechage'
WHERE short_name = 'sc' AND show_name IS DISTINCT FROM 'Repechage';

-- Keep the historical contest rules intact and put the national-final ballot
-- policy in front of them. The schema contains the equivalent consolidated
-- function for clean database installs.
ALTER FUNCTION ballot_entry_rule(bigint, text, bigint, text, bigint)
RENAME TO contest_ballot_entry_rule;

CREATE FUNCTION ballot_entry_rule(
    p_show_id bigint,
    p_result_mode text,
    p_voter_id bigint,
    p_country_id text,
    p_song_id bigint
)
RETURNS TABLE (
    rule_kind text,
    rule_reason text,
    required_score integer,
    score_cap integer
) AS $$
DECLARE
    v_national_final_id bigint;
    v_max_score integer;
    v_scored_positions integer;
    v_song_submitter_id bigint;
    v_entry_count integer;
    v_owned_entry_count integer;
BEGIN
    SELECT show.national_final_id, MAX(point.score), COUNT(point.id)
    INTO v_national_final_id, v_max_score, v_scored_positions
    FROM show
    JOIN point ON point.point_system_id = show.point_system_id
    WHERE show.id = p_show_id
    GROUP BY show.national_final_id;

    IF v_national_final_id IS NULL THEN
        RETURN QUERY
        SELECT contest.rule_kind, contest.rule_reason,
               contest.required_score, contest.score_cap
        FROM contest_ballot_entry_rule(
            p_show_id, p_result_mode, p_voter_id, p_country_id, p_song_id
        ) AS contest;
        RETURN;
    END IF;

    IF p_result_mode NOT IN ('official', 'revote') THEN
        RAISE EXCEPTION 'Unknown result mode: %', p_result_mode;
    END IF;

    SELECT song.submitter_id
    INTO v_song_submitter_id
    FROM song_show
    JOIN current_song AS song ON song.id = song_show.song_id
    WHERE song_show.show_id = p_show_id AND song.id = p_song_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Song % does not belong to show %', p_song_id, p_show_id;
    END IF;

    SELECT COUNT(*), COUNT(*) FILTER (WHERE song.submitter_id = p_voter_id)
    INTO v_entry_count, v_owned_entry_count
    FROM song_show
    JOIN current_song AS song ON song.id = song_show.song_id
    WHERE song_show.show_id = p_show_id;

    IF v_entry_count - v_owned_entry_count >= v_scored_positions
       AND v_song_submitter_id = p_voter_id THEN
        rule_kind := 'FORBIDDEN';
        rule_reason := 'owner';
        required_score := NULL;
        score_cap := 0;
    ELSE
        rule_kind := 'NORMAL';
        rule_reason := NULL;
        required_score := NULL;
        score_cap := v_max_score;
    END IF;
    RETURN NEXT;
END;
$$ LANGUAGE plpgsql STABLE;

CREATE TABLE show_progression (
    source_show_id bigint NOT NULL
        REFERENCES show (id) ON UPDATE RESTRICT ON DELETE CASCADE,
    target_show_id bigint NOT NULL
        REFERENCES show (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    qualifier_count smallint NOT NULL CHECK (qualifier_count > 0),
    priority smallint NOT NULL CHECK (priority > 0),
    PRIMARY KEY (source_show_id, target_show_id),
    UNIQUE (source_show_id, priority),
    CHECK (source_show_id <> target_show_id)
);

CREATE INDEX show_progression_target_idx ON show_progression (target_show_id);

CREATE FUNCTION validate_show_progression()
RETURNS trigger AS $$
DECLARE
    source_year bigint;
    source_nf bigint;
    target_year bigint;
    target_nf bigint;
BEGIN
    SELECT year_id, national_final_id INTO source_year, source_nf
    FROM show WHERE id = NEW.source_show_id;
    SELECT year_id, national_final_id INTO target_year, target_nf
    FROM show WHERE id = NEW.target_show_id;

    IF source_year IS DISTINCT FROM target_year
       OR source_nf IS DISTINCT FROM target_nf THEN
        RAISE EXCEPTION 'Progression shows must belong to the same event';
    END IF;

    IF EXISTS (
        WITH RECURSIVE descendants(id) AS (
            SELECT NEW.target_show_id
            UNION
            SELECT progression.target_show_id
            FROM show_progression AS progression
            JOIN descendants ON progression.source_show_id = descendants.id
        )
        SELECT 1 FROM descendants WHERE id = NEW.source_show_id
    ) THEN
        RAISE EXCEPTION 'Show progression cannot contain a cycle';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_validate_show_progression
    BEFORE INSERT OR UPDATE ON show_progression
    FOR EACH ROW EXECUTE FUNCTION validate_show_progression();

INSERT INTO show_progression (
    source_show_id, target_show_id, qualifier_count, priority
)
SELECT source.id, target.id, source.dtf, 1
FROM show AS source
JOIN show AS target
  ON target.year_id = source.year_id
 AND target.national_final_id IS NOT DISTINCT FROM source.national_final_id
 AND target.show_type = 'f'
WHERE source.dtf > 0
ON CONFLICT (source_show_id, target_show_id) DO UPDATE
SET qualifier_count = EXCLUDED.qualifier_count,
    priority = EXCLUDED.priority;

INSERT INTO show_progression (
    source_show_id, target_show_id, qualifier_count, priority
)
SELECT source.id, target.id, COALESCE(source.sc, 0) + COALESCE(source.special, 0), 2
FROM show AS source
JOIN show AS target
  ON target.year_id = source.year_id
 AND target.national_final_id IS NOT DISTINCT FROM source.national_final_id
 AND target.show_type = 'sc'
WHERE COALESCE(source.sc, 0) + COALESCE(source.special, 0) > 0
ON CONFLICT (source_show_id, target_show_id) DO UPDATE
SET qualifier_count = EXCLUDED.qualifier_count,
    priority = EXCLUDED.priority;

CREATE TABLE show_qualifier (
    source_show_id bigint NOT NULL,
    target_show_id bigint NOT NULL,
    song_id bigint NOT NULL,
    qualifier_order smallint,
    is_special boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (source_show_id, target_show_id, song_id),
    UNIQUE (target_show_id, song_id),
    UNIQUE (source_show_id, target_show_id, qualifier_order),
    FOREIGN KEY (source_show_id, target_show_id)
        REFERENCES show_progression (source_show_id, target_show_id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    FOREIGN KEY (song_id, source_show_id)
        REFERENCES song_show (song_id, show_id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    FOREIGN KEY (song_id, target_show_id)
        REFERENCES song_show (song_id, show_id)
        ON UPDATE RESTRICT ON DELETE CASCADE
);

-- Preserve actual historical advancements. The intersection with the target
-- lineup prevents a cached ranking from inventing a qualification that was
-- never applied. The old per-show special quota is used only for this one-time
-- conversion into per-song flags.
INSERT INTO show_qualifier (
    source_show_id, target_show_id, song_id, qualifier_order, is_special
)
WITH boundaries AS (
    SELECT progression.source_show_id, progression.target_show_id,
           progression.priority,
           SUM(progression.qualifier_count) OVER (
               PARTITION BY progression.source_show_id
               ORDER BY progression.priority
           ) AS cutoff,
           COALESCE(source.dtf, 0) AS direct_count,
           COALESCE(source.special, 0) AS special_count
    FROM show_progression AS progression
    JOIN show AS source ON source.id = progression.source_show_id
)
SELECT boundaries.source_show_id, boundaries.target_show_id, results.song_id,
       target_entry.qualifier_order,
       results.place > boundaries.direct_count
       AND results.place <= boundaries.direct_count + boundaries.special_count
FROM boundaries
JOIN country_show_results AS results
  ON results.show_id = boundaries.source_show_id
 AND results.result_mode = 'official'
 AND results.place <= boundaries.cutoff
JOIN song_show AS target_entry
  ON target_entry.show_id = boundaries.target_show_id
 AND target_entry.song_id = results.song_id
ON CONFLICT (target_show_id, song_id) DO NOTHING;

ALTER TABLE country_show_results
    ADD COLUMN special_qualifier boolean NOT NULL DEFAULT false;

CREATE FUNCTION show_progression_status(
    p_show_id bigint, p_place bigint
)
RETURNS text AS $$
    SELECT COALESCE((
        SELECT boundaries.target_short_name
        FROM (
            SELECT target.short_name AS target_short_name,
                   progression.priority,
                   SUM(progression.qualifier_count) OVER (
                       ORDER BY progression.priority
                   ) AS cutoff
            FROM show_progression AS progression
            JOIN show AS target ON target.id = progression.target_show_id
            WHERE progression.source_show_id = p_show_id
        ) AS boundaries
        WHERE p_place <= boundaries.cutoff
        ORDER BY boundaries.priority
        LIMIT 1
    ), 'nq');
$$ LANGUAGE sql STABLE;

CREATE FUNCTION show_result_progression_status(
    p_show_id bigint,
    p_song_id bigint,
    p_place bigint,
    p_result_mode text
)
RETURNS text AS $$
    SELECT COALESCE(
        CASE WHEN p_result_mode = 'official' THEN (
            SELECT target.short_name
            FROM show_qualifier AS qualifier
            JOIN show AS target ON target.id = qualifier.target_show_id
            WHERE qualifier.source_show_id = p_show_id
              AND qualifier.song_id = p_song_id
        ) END,
        show_progression_status(p_show_id, p_place)
    );
$$ LANGUAGE sql STABLE;

CREATE FUNCTION show_result_special_qualifier(
    p_show_id bigint,
    p_song_id bigint,
    p_result_mode text
)
RETURNS boolean AS $$
    SELECT p_result_mode = 'official' AND EXISTS (
        SELECT 1 FROM show_qualifier
        WHERE source_show_id = p_show_id
          AND song_id = p_song_id
          AND is_special
    );
$$ LANGUAGE sql STABLE;

DO $$
DECLARE
    definition text;
BEGIN
    SELECT pg_get_functiondef(
        'refresh_show_results_for_mode(bigint,text)'::regprocedure
    ) INTO definition;

    definition := replace(
        definition,
        'sh.id, sh.year_id, sh.dtf, sh.sc, sh.special,',
        'sh.id, sh.year_id,'
    );
    definition := replace(
        definition,
        '            si.dtf,
            si.sc,
            si.special,
',
        ''
    );
    definition := replace(
        definition,
        'si.year_id, si.dtf, si.sc, si.special, vbc.cnt, ec.score_cap',
        'si.year_id, vbc.cnt, ec.score_cap'
    );
    definition := replace(
        definition,
        'CASE
            WHEN n.short_name = ''f'' THEN NULL
            WHEN n.place <= COALESCE(n.dtf, 0) THEN ''dtf''
            WHEN n.place <= COALESCE(n.dtf, 0) + COALESCE(n.special, 0)
                THEN ''special''
            WHEN n.place <= COALESCE(n.dtf, 0) + COALESCE(n.special, 0)
                    + COALESCE(n.sc, 0)
                THEN ''sc''
            ELSE ''nq''
        END',
        'CASE WHEN EXISTS (
            SELECT 1 FROM show_progression
            WHERE source_show_id = n.show_id
        ) THEN show_result_progression_status(
            n.show_id, n.song_id, n.place, p_result_mode
        ) ELSE NULL END,
        show_result_special_qualifier(
            n.show_id, n.song_id, p_result_mode
        )'
    );
    definition := replace(
        definition,
        'adjusted_max_possible_points, points_midpoint, entry_status, max_pts,',
        'adjusted_max_possible_points, points_midpoint, entry_status,
        special_qualifier, max_pts,'
    );
    IF definition ~ '\m(n|si|sh)\.(dtf|sc|special)\M'
       OR definition NOT LIKE '%show_result_special_qualifier%' THEN
        RAISE EXCEPTION 'Could not update result refresh for show progression';
    END IF;
    EXECUTE definition;
END;
$$;

ALTER TABLE show DROP COLUMN dtf;
ALTER TABLE show DROP COLUMN sc;
ALTER TABLE show DROP COLUMN special;

CREATE OR REPLACE FUNCTION refresh_year_results(p_year_id bigint)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
    DELETE FROM country_year_results WHERE year_id = p_year_id;

    WITH RECURSIVE paths(source_show_id, target_show_id, distance) AS (
        SELECT source_show_id, target_show_id, 1 FROM show_progression
        UNION ALL
        SELECT paths.source_show_id, progression.target_show_id, paths.distance + 1
        FROM paths
        JOIN show_progression AS progression
          ON progression.source_show_id = paths.target_show_id
    ),
    show_tiers AS (
        SELECT show.id AS show_id, COALESCE(MAX(paths.distance), 0) + 1 AS tier
        FROM show
        LEFT JOIN paths ON paths.source_show_id = show.id
        WHERE show.year_id = p_year_id AND show.national_final_id IS NULL
        GROUP BY show.id
    ),
    candidates AS (
        SELECT csr.*, show_tiers.tier,
               ROW_NUMBER() OVER (
                   PARTITION BY csr.song_id
                   ORDER BY show_tiers.tier, csr.place, csr.show_id
               ) AS reached_order,
               STRING_AGG(
                   LPAD(points.key, 3, '0') || ':' || LPAD(points.value, 3, '0'),
                   ',' ORDER BY points.key::integer DESC
               ) AS countback
        FROM country_show_results AS csr
        JOIN show_tiers ON show_tiers.show_id = csr.show_id
        LEFT JOIN LATERAL jsonb_each_text(csr.point_distribution) AS points ON true
        WHERE csr.year_id = p_year_id AND csr.result_mode = 'official'
        GROUP BY csr.country_id, csr.country_name, csr.show_id, csr.song_id,
                 csr.running_order, csr.show_name, csr.short_name, csr.year_id,
                 csr.total_points, csr.total_votes_received, csr.point_distribution,
                 csr.place, csr.total_countries, csr.placement_percentage,
                 csr.max_possible_points, csr.points_percentage, csr.entry_status,
                 csr.max_pts, csr.total_voters, csr.result_mode,
                 csr.adjusted_points_percentage, csr.adjusted_max_possible_points,
                 csr.points_midpoint, csr.calculated_at, show_tiers.tier
    ),
    reached AS (
        SELECT * FROM candidates WHERE reached_order = 1
    ),
    all_ranked AS (
        SELECT country_id, country_name, year_id, song_id,
               ROW_NUMBER() OVER (
                   ORDER BY tier, points_percentage DESC, total_voters DESC,
                            countback DESC NULLS LAST,
                            running_order NULLS LAST, show_id, song_id
               )::integer AS place
        FROM reached
    ),
    totals AS (
        SELECT COUNT(*) AS total_countries FROM all_ranked
    )
    INSERT INTO country_year_results (
        country_id, country_name, year_id, song_id,
        place, total_countries, placement_percentage
    )
    SELECT all_ranked.country_id, all_ranked.country_name,
           all_ranked.year_id, all_ranked.song_id, all_ranked.place,
           totals.total_countries,
           CASE WHEN totals.total_countries = 1 THEN 100
                ELSE ROUND(
                    ((totals.total_countries - all_ranked.place)::numeric
                    / (totals.total_countries - 1)::numeric) * 100,
                    3
                )
           END
    FROM all_ranked CROSS JOIN totals
    ORDER BY all_ranked.place;
END;
$$;

ALTER TABLE song_show DROP COLUMN qualifier_order;

DELETE FROM show_result_refresh_queue AS queue
WHERE NOT EXISTS (
    SELECT 1 FROM show WHERE show.id = queue.show_id
);

ALTER TABLE show_result_refresh_queue
ADD CONSTRAINT show_result_refresh_queue_show_fk
FOREIGN KEY (show_id) REFERENCES show (id)
ON UPDATE RESTRICT ON DELETE CASCADE;

CREATE OR REPLACE FUNCTION process_show_result_refresh_queue()
RETURNS TRIGGER AS $$
BEGIN
    -- A deferred refresh can outlive the show or its point configuration
    -- when either is removed later in the same transaction.
    IF NOT EXISTS (
        SELECT 1
        FROM show
        JOIN point ON point.point_system_id = show.point_system_id
        WHERE show.id = NEW.show_id
    ) THEN
        DELETE FROM country_show_results
        WHERE show_id = NEW.show_id AND result_mode = NEW.result_mode;
        DELETE FROM show_result_refresh_queue
        WHERE show_id = NEW.show_id AND result_mode = NEW.result_mode;
        RETURN NEW;
    END IF;

    IF NEW.result_mode = 'revote' THEN
        PERFORM refresh_revote_penalties(NEW.show_id);
    END IF;

    PERFORM refresh_show_results_for_mode(NEW.show_id, NEW.result_mode);

    DELETE FROM show_result_refresh_queue
    WHERE show_id = NEW.show_id AND result_mode = NEW.result_mode;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMIT;
