BEGIN;

-- Per-song time signatures with start times, paralleling
-- song_key_signature. Mixed-meter sections are modelled by leaving
-- both numerator and denominator NULL; numerator/denominator are
-- required to come as a pair (you can't have one without the other).

CREATE TABLE IF NOT EXISTS song_time_signature (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    song_id bigint NOT NULL REFERENCES song (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    start_seconds integer NOT NULL DEFAULT 0,
    numerator smallint,
    denominator smallint,
    UNIQUE (song_id, start_seconds),
    CHECK (start_seconds >= 0),
    CHECK ((numerator IS NULL) = (denominator IS NULL)),
    CHECK (numerator IS NULL OR numerator > 0),
    CHECK (denominator IS NULL OR denominator IN (1, 2, 4, 8, 16, 32))
);

CREATE INDEX IF NOT EXISTS song_time_signature_song_idx
    ON song_time_signature (song_id, start_seconds);

COMMIT;
