-- Messaging, shared administrator inboxes, per-user read state, and avatars.
--
-- This migration intentionally contains the feature's final schema directly.
-- The feature was consolidated before release so production records one
-- migration instead of the intermediate development steps.

BEGIN;

CREATE TABLE account_avatar (
    account_id bigint PRIMARY KEY
        REFERENCES account (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    image_data bytea NOT NULL,
    media_type text NOT NULL,
    width smallint NOT NULL,
    height smallint NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT account_avatar_media_type_check
        CHECK (media_type IN ('image/png', 'image/jpeg', 'image/webp')),
    CONSTRAINT account_avatar_width_check
        CHECK (width BETWEEN 1 AND 512),
    CONSTRAINT account_avatar_height_check
        CHECK (height BETWEEN 1 AND 512),
    CONSTRAINT account_avatar_image_data_length_check
        CHECK (octet_length(image_data) BETWEEN 1 AND 2097152)
);

CREATE TABLE conversation (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    subject text NOT NULL,
    admin_accessible boolean NOT NULL DEFAULT false,
    created_by_admin boolean NOT NULL DEFAULT false,
    system_conversation boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    subject_search_vector tsvector GENERATED ALWAYS AS (
        to_tsvector('simple', subject)
    ) STORED,
    CONSTRAINT conversation_subject_not_blank
        CHECK (subject ~ '[^[:space:]]'),
    CONSTRAINT conversation_subject_length
        CHECK (char_length(subject) <= 200),
    CONSTRAINT conversation_admin_origin_check
        CHECK (
            NOT created_by_admin
            OR (NOT system_conversation AND admin_accessible)
        )
);

CREATE TABLE conversation_participant (
    conversation_id bigint NOT NULL
        REFERENCES conversation (id) ON UPDATE RESTRICT ON DELETE CASCADE,
    account_id bigint NOT NULL
        REFERENCES account (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    role text NOT NULL DEFAULT 'participant',
    email_notifications boolean NOT NULL DEFAULT false,
    joined_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (conversation_id, account_id),
    CONSTRAINT conversation_participant_role_check
        CHECK (role IN ('owner', 'admin', 'participant'))
);

CREATE TABLE message (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    conversation_id bigint NOT NULL
        REFERENCES conversation (id) ON UPDATE RESTRICT ON DELETE CASCADE,
    sender_id bigint
        REFERENCES account (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    sender_kind text NOT NULL,
    body text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    body_search_vector tsvector GENERATED ALWAYS AS (
        to_tsvector(
            'simple',
            regexp_replace(
                body,
                '\[/?(b|i|u|s|o|sm|xl|pre|code|c(=[[:alpha:]]+)?|bg(=[[:alpha:]]+)?)\]',
                ' ',
                'gi'
            )
        )
    ) STORED,
    CONSTRAINT message_sender_kind_check
        CHECK (sender_kind IN ('participant', 'admin', 'system')),
    CONSTRAINT message_sender_check
        CHECK (
            (sender_kind = 'system' AND sender_id IS NULL)
            OR (sender_kind IN ('participant', 'admin') AND sender_id IS NOT NULL)
        ),
    CONSTRAINT message_body_not_blank
        CHECK (body ~ '[^[:space:]]'),
    CONSTRAINT message_body_length
        CHECK (char_length(body) <= 5000)
);

CREATE TABLE conversation_read_state (
    conversation_id bigint NOT NULL
        REFERENCES conversation (id) ON UPDATE RESTRICT ON DELETE CASCADE,
    account_id bigint NOT NULL
        REFERENCES account (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    last_read_message_id bigint NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (conversation_id, account_id),
    CONSTRAINT conversation_read_state_message_id_check
        CHECK (last_read_message_id >= 0)
);

CREATE INDEX conversation_subject_search_idx
    ON conversation USING gin (subject_search_vector);
CREATE INDEX conversation_admin_accessible_idx
    ON conversation (id) WHERE admin_accessible;
CREATE INDEX conversation_participant_account_idx
    ON conversation_participant (account_id, conversation_id);
CREATE UNIQUE INDEX conversation_single_owner_idx
    ON conversation_participant (conversation_id) WHERE role = 'owner';
CREATE INDEX conversation_read_state_account_idx
    ON conversation_read_state (account_id, conversation_id);
CREATE INDEX message_body_search_idx
    ON message USING gin (body_search_vector);
CREATE INDEX message_conversation_id_idx
    ON message (conversation_id, id);
CREATE INDEX message_conversation_created_idx
    ON message (conversation_id, created_at DESC, id DESC);
CREATE INDEX message_sender_created_idx
    ON message (sender_id, created_at DESC, id DESC)
    WHERE sender_id IS NOT NULL;
CREATE INDEX message_created_idx ON message (created_at DESC, id DESC);

CREATE OR REPLACE FUNCTION validate_conversation_participation_state(
    target_conversation_id bigint
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    target_conversation conversation%ROWTYPE;
BEGIN
    SELECT *
    INTO target_conversation
    FROM conversation
    WHERE id = target_conversation_id;

    IF NOT FOUND THEN
        RETURN;
    END IF;

    IF target_conversation.system_conversation THEN
        IF EXISTS (
            SELECT 1
            FROM conversation_participant
            WHERE conversation_id = target_conversation_id AND role = 'owner'
        ) THEN
            RAISE EXCEPTION 'system conversations cannot have an owner';
        END IF;
    ELSIF (
        SELECT COUNT(*)
        FROM conversation_participant
        WHERE conversation_id = target_conversation_id AND role = 'owner'
    ) <> 1 THEN
        RAISE EXCEPTION 'non-system conversations require exactly one owner';
    END IF;

    IF NOT target_conversation.admin_accessible AND EXISTS (
        SELECT 1
        FROM conversation_participant
        WHERE conversation_id = target_conversation_id AND role = 'admin'
    ) THEN
        RAISE EXCEPTION 'admin participants require shared admin access';
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION validate_conversation_participation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM validate_conversation_participation_state(NEW.id);
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION validate_participant_conversation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        PERFORM validate_conversation_participation_state(OLD.conversation_id);
        RETURN OLD;
    END IF;

    IF TG_OP = 'UPDATE' AND OLD.conversation_id <> NEW.conversation_id THEN
        PERFORM validate_conversation_participation_state(OLD.conversation_id);
    END IF;
    PERFORM validate_conversation_participation_state(NEW.conversation_id);
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION validate_admin_participant_role()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.role = 'admin' THEN
        IF NOT EXISTS (
            SELECT 1
            FROM conversation
            WHERE id = NEW.conversation_id AND admin_accessible
        ) THEN
            RAISE EXCEPTION 'admin participants require shared admin access';
        END IF;
        IF NOT EXISTS (
            SELECT 1
            FROM account
            JOIN account_role ON account_role.name = account.role
            WHERE account.id = NEW.account_id
              AND account_role.can_view_restricted
        ) THEN
            RAISE EXCEPTION 'admin participant does not have admin access';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION validate_message_sender()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    target_conversation conversation%ROWTYPE;
BEGIN
    SELECT *
    INTO target_conversation
    FROM conversation
    WHERE id = NEW.conversation_id;

    IF NOT FOUND THEN
        -- The foreign key will produce the canonical error after this trigger.
        RETURN NEW;
    END IF;

    IF NEW.sender_kind = 'system' THEN
        IF NOT target_conversation.system_conversation THEN
            RAISE EXCEPTION 'system messages require a system conversation';
        END IF;
    ELSIF NEW.sender_kind = 'participant' THEN
        IF target_conversation.system_conversation THEN
            RAISE EXCEPTION 'system conversations do not accept replies';
        END IF;
        IF NOT EXISTS (
            SELECT 1
            FROM conversation_participant
            WHERE conversation_id = NEW.conversation_id
              AND account_id = NEW.sender_id
              AND role IN ('owner', 'participant')
        ) THEN
            RAISE EXCEPTION 'sender is not an owner or ordinary participant';
        END IF;
    ELSIF NEW.sender_kind = 'admin' THEN
        IF target_conversation.system_conversation THEN
            RAISE EXCEPTION 'system conversations do not accept replies';
        END IF;
        IF NOT target_conversation.admin_accessible THEN
            RAISE EXCEPTION 'conversation does not permit shared admin access';
        END IF;
        IF NOT EXISTS (
            SELECT 1
            FROM account
            JOIN account_role ON account_role.name = account.role
            WHERE account.id = NEW.sender_id
              AND account_role.can_view_restricted
        ) THEN
            RAISE EXCEPTION 'admin sender does not have admin access';
        END IF;
        IF NOT EXISTS (
            SELECT 1
            FROM conversation_participant
            WHERE conversation_id = NEW.conversation_id
              AND account_id = NEW.sender_id
              AND (
                  role = 'admin'
                  OR (role = 'owner' AND target_conversation.created_by_admin)
              )
        ) THEN
            RAISE EXCEPTION 'admin sender is not an admin participant';
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER validate_message_sender_before_write
    BEFORE INSERT OR UPDATE OF conversation_id, sender_id, sender_kind ON message
    FOR EACH ROW
    EXECUTE FUNCTION validate_message_sender();

CREATE CONSTRAINT TRIGGER validate_conversation_participation_after_write
    AFTER INSERT OR UPDATE ON conversation
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW
    EXECUTE FUNCTION validate_conversation_participation();

CREATE CONSTRAINT TRIGGER validate_participant_conversation_after_write
    AFTER INSERT OR DELETE OR UPDATE ON conversation_participant
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW
    EXECUTE FUNCTION validate_participant_conversation();

CREATE TRIGGER validate_admin_participant_role_before_write
    BEFORE INSERT OR UPDATE OF conversation_id, account_id, role
    ON conversation_participant
    FOR EACH ROW
    EXECUTE FUNCTION validate_admin_participant_role();

COMMIT;
