BEGIN;

-- Per-song key signatures with start times, allowing keys to change
-- across the song. Tonic and mode are stored as free text so the UI can
-- offer a curated dropdown plus an "Other" escape hatch. Atonal
-- sections are modelled by leaving both tonic and mode NULL. The
-- ``microtonal`` flag is an independent annotation for songs using
-- non-12-TET tunings (xenharmonic, n-EDO, etc.) so they can be queried
-- as a group regardless of the tonic/mode spelling chosen.
--
-- Uniqueness on (song_id, start_seconds) prevents two keys claiming the
-- same instant; the same key may legitimately appear at multiple start
-- times as the song modulates back and forth.

CREATE TABLE IF NOT EXISTS song_key_signature (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    song_id bigint NOT NULL REFERENCES song (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    start_seconds integer NOT NULL DEFAULT 0,
    tonic text,
    mode text,
    microtonal boolean NOT NULL DEFAULT FALSE,
    UNIQUE (song_id, start_seconds),
    CHECK (start_seconds >= 0)
);

CREATE INDEX IF NOT EXISTS song_key_signature_song_idx
    ON song_key_signature (song_id, start_seconds);

COMMIT;
