BEGIN;

-- Resolve the browser MIME type for media URLs that the radio can play
-- directly. Query strings and fragments do not affect the file extension.
CREATE OR REPLACE FUNCTION radio_media_type(p_url text)
RETURNS text
LANGUAGE sql
IMMUTABLE
STRICT
PARALLEL SAFE
AS $$
    SELECT CASE lower(
        substring(
            split_part(split_part(p_url, '#', 1), '?', 1)
            FROM '\.([^.]+)$'
        )
    )
        WHEN 'mp4' THEN 'video/mp4'
        WHEN 'm4v' THEN 'video/mp4'
        WHEN 'm4a' THEN 'audio/mp4'
        WHEN 'webm' THEN 'video/webm'
        WHEN 'ogg' THEN 'video/ogg'
        -- These files contain H.264/AAC media that browsers accept when
        -- advertised as MP4 rather than video/quicktime.
        WHEN 'mov' THEN 'video/mp4'
        ELSE NULL
    END
$$;

-- The radio schedule is also its immutable play history. Song metadata is
-- copied into each row intentionally: later catalogue edits or deletion must
-- not rewrite what the station had scheduled.
CREATE TABLE radio_slot (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    starts_at timestamptz NOT NULL,
    ends_at timestamptz NOT NULL,
    source_song_id bigint NOT NULL,
    title text,
    artist text,
    media_url text NOT NULL,
    media_type text NOT NULL,
    media_duration_seconds double precision NOT NULL,
    poster_url text,
    vtt_url text,
    country_code text NOT NULL,
    country_name text NOT NULL,
    year_id bigint NOT NULL,
    year_label text NOT NULL,
    pool_size_at_queue integer NOT NULL,
    queued_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    play_window tstzrange GENERATED ALWAYS AS (
        tstzrange(starts_at, ends_at, '[)')
    ) STORED,
    CONSTRAINT radio_slot_time_order CHECK (ends_at > starts_at),
    CONSTRAINT radio_slot_duration_positive CHECK (media_duration_seconds > 0),
    CONSTRAINT radio_slot_pool_size_positive CHECK (pool_size_at_queue > 0),
    CONSTRAINT radio_slot_no_overlap EXCLUDE USING gist (play_window WITH &&)
);

CREATE INDEX radio_slot_starts_at_idx ON radio_slot (starts_at);
CREATE INDEX radio_slot_ends_at_idx ON radio_slot (ends_at);

-- Append a random, non-repeating batch when fewer than the requested number
-- of unstarted slots remain. The advisory lock serializes the low-watermark
-- transition across all application workers; the second count prevents a
-- waiter from adding another batch after the first transaction commits.
CREATE OR REPLACE FUNCTION refill_radio_queue(
    p_at timestamptz DEFAULT clock_timestamp(),
    p_minimum_remaining integer DEFAULT 10,
    p_batch_size integer DEFAULT 50
)
RETURNS integer
LANGUAGE plpgsql
VOLATILE
AS $$
DECLARE
    v_remaining integer;
    v_append_at timestamptz;
    v_inserted integer;
BEGIN
    IF p_at IS NULL THEN
        RAISE EXCEPTION 'p_at must not be null';
    END IF;
    IF p_minimum_remaining < 1 THEN
        RAISE EXCEPTION 'p_minimum_remaining must be positive';
    END IF;
    IF p_batch_size < 1 THEN
        RAISE EXCEPTION 'p_batch_size must be positive';
    END IF;

    SELECT count(*)::integer
    INTO v_remaining
    FROM radio_slot
    WHERE starts_at >= p_at;

    IF v_remaining >= p_minimum_remaining THEN
        RETURN 0;
    END IF;

    PERFORM pg_advisory_xact_lock(20260720, 1);

    SELECT count(*)::integer
    INTO v_remaining
    FROM radio_slot
    WHERE starts_at >= p_at;

    IF v_remaining >= p_minimum_remaining THEN
        RETURN 0;
    END IF;

    SELECT greatest(p_at, COALESCE(max(ends_at), p_at))
    INTO v_append_at
    FROM radio_slot;

    WITH eligible AS MATERIALIZED (
        SELECT
            song.id AS source_song_id,
            song.title,
            song.artist,
            song.video_link AS media_url,
            radio_media_type(song.video_link) AS media_type,
            song.duration AS media_duration_seconds,
            song.poster_link AS poster_url,
            song.vtt_link AS vtt_url,
            country.id AS country_code,
            country.name AS country_name,
            year.id AS year_id,
            COALESCE(year.special_name, year.id::text) AS year_label
        FROM song
        JOIN year ON year.id = song.year_id
        JOIN country ON country.id = song.country_id
        WHERE year.status = 'closed'
          AND NOT song.is_placeholder
          AND song.video_link IS NOT NULL
          AND song.duration > 0
          AND radio_media_type(song.video_link) IS NOT NULL
    ),
    randomized AS MATERIALIZED (
        SELECT
            eligible.*,
            random() AS random_order,
            count(*) OVER ()::integer AS pool_size_at_queue
        FROM eligible
    ),
    candidates AS MATERIALIZED (
        SELECT *
        FROM randomized
        ORDER BY random_order, source_song_id
        LIMIT p_batch_size
    ),
    timed AS (
        SELECT
            candidates.*,
            COALESCE(
                sum(media_duration_seconds) OVER (
                    ORDER BY random_order, source_song_id
                    ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING
                ),
                0.0
            ) AS seconds_before,
            sum(media_duration_seconds) OVER (
                ORDER BY random_order, source_song_id
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS seconds_through
        FROM candidates
    )
    INSERT INTO radio_slot (
        starts_at,
        ends_at,
        source_song_id,
        title,
        artist,
        media_url,
        media_type,
        media_duration_seconds,
        poster_url,
        vtt_url,
        country_code,
        country_name,
        year_id,
        year_label,
        pool_size_at_queue
    )
    SELECT
        v_append_at + make_interval(secs => timed.seconds_before),
        v_append_at + make_interval(secs => timed.seconds_through),
        timed.source_song_id,
        timed.title,
        timed.artist,
        timed.media_url,
        timed.media_type,
        timed.media_duration_seconds,
        timed.poster_url,
        timed.vtt_url,
        timed.country_code,
        timed.country_name,
        timed.year_id,
        timed.year_label,
        timed.pool_size_at_queue
    FROM timed
    ORDER BY timed.random_order, timed.source_song_id;

    GET DIAGNOSTICS v_inserted = ROW_COUNT;
    RETURN v_inserted;
END;
$$;

-- This is the application's one-round-trip read. It fills the low queue when
-- necessary, then returns the slot at the exact same database timestamp.
CREATE OR REPLACE FUNCTION get_current_radio_slot(
    p_at timestamptz DEFAULT clock_timestamp()
)
RETURNS TABLE (
    server_time timestamptz,
    slot_id bigint,
    starts_at timestamptz,
    ends_at timestamptz,
    source_song_id bigint,
    title text,
    artist text,
    media_url text,
    media_type text,
    media_duration_seconds double precision,
    poster_url text,
    vtt_url text,
    country_code text,
    country_name text,
    year_id bigint,
    year_label text,
    pool_size_at_queue integer,
    queued_at timestamptz
)
LANGUAGE plpgsql
VOLATILE
AS $$
BEGIN
    PERFORM refill_radio_queue(p_at);

    RETURN QUERY
    SELECT
        p_at,
        slot.id,
        slot.starts_at,
        slot.ends_at,
        slot.source_song_id,
        slot.title,
        slot.artist,
        slot.media_url,
        slot.media_type,
        slot.media_duration_seconds,
        slot.poster_url,
        slot.vtt_url,
        slot.country_code,
        slot.country_name,
        slot.year_id,
        slot.year_label,
        slot.pool_size_at_queue,
        slot.queued_at
    FROM radio_slot AS slot
    WHERE slot.play_window @> p_at
    ORDER BY slot.starts_at DESC
    LIMIT 1;
END;
$$;

-- Human-oriented inspection of the currently playing and queued slots.
CREATE OR REPLACE VIEW radio_queue AS
SELECT
    slot.id AS slot_id,
    CASE
        WHEN slot.starts_at <= statement_timestamp() THEN 'playing'
        ELSE 'queued'
    END AS status,
    slot.starts_at,
    slot.ends_at,
    slot.source_song_id,
    slot.title,
    slot.artist,
    slot.media_url,
    slot.media_type,
    slot.media_duration_seconds,
    slot.poster_url,
    slot.vtt_url,
    slot.country_code,
    slot.country_name,
    slot.year_id,
    slot.year_label,
    slot.pool_size_at_queue,
    slot.queued_at
FROM radio_slot AS slot
WHERE slot.ends_at > statement_timestamp();

COMMIT;
