BEGIN;

CREATE TABLE api_token (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL REFERENCES account (id) ON DELETE CASCADE,
    token_hash bytea NOT NULL,
    label text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at timestamptz,
    UNIQUE (token_hash)
);

CREATE INDEX idx_api_token_user_id ON api_token (user_id);
CREATE INDEX idx_api_token_hash ON api_token (token_hash);

COMMIT;
