BEGIN;

CREATE TABLE password_reset_token (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_id bigint NOT NULL
        REFERENCES account (id) ON UPDATE RESTRICT ON DELETE CASCADE,
    token_hash bytea NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamptz NOT NULL,
    used_at timestamptz,
    CONSTRAINT password_reset_token_expiry_check CHECK (expires_at > created_at)
);

CREATE INDEX password_reset_token_account_idx
    ON password_reset_token (account_id, expires_at DESC);

UPDATE conversation_participant AS participant
SET email_notifications = true
FROM account, conversation
WHERE account.id = participant.account_id
  AND conversation.id = participant.conversation_id
  AND (conversation.created_by_admin OR conversation.system_conversation)
  AND NULLIF(BTRIM(account.email), '') IS NOT NULL;

COMMIT;
